import { Schema } from "effect";
import { DataViewObjectDefinitionsV1_3_0 } from "../formatting-object-definitions/version-1.3.0.js";
import {
  Background,
  Border,
  closed,
  Divider,
  DropShadow,
  LockAspect,
  Padding,
  Spacing,
  StylePreset,
  SubTitle,
  Title,
  VisualContainerGeneralFormattingObjects,
  VisualHeader,
  VisualHeaderTooltip,
  VisualLink,
  VisualTooltip,
} from "../shared.js";
import {
  AIDecompositionMethod,
  AILevelInformation,
  ExpansionStateV1_5_0,
  LevelExpansionStateV1_5_0,
  NodeExpansionStateV1_5_0,
  ProjectionStateV1_8_0,
  QuerySortV1_5_0,
  QueryV1_8_0,
  RoleFieldParameterV1_8_0,
  RoleProjectionV1_5_0,
  RootExpansionStateV1_5_0,
  SortDefinitionV1_5_0,
  SortDirection,
  VisualContainerFormattingObjectsV1_8_0,
  VisualQueryOptions,
  VisualSyncGroup,
} from "./shared.js";

export type VisualConfigurationV1_8_0 = {
  readonly $schema: "https://developer.microsoft.com/json-schemas/fabric/item/report/definition/visualConfiguration/1.8.0/schema.json";
  readonly visualType: string;
  readonly autoSelectVisualType?: boolean;
  readonly query?: QueryV1_8_0;
  readonly expansionStates?: ReadonlyArray<ExpansionStateV1_5_0>;
  readonly objects?: DataViewObjectDefinitionsV1_3_0;
  readonly visualContainerObjects?: VisualContainerFormattingObjectsV1_8_0;
  readonly syncGroup?: VisualSyncGroup;
  readonly drillFilterOtherVisuals?: boolean;
};

export const VisualConfigurationV1_8_0: Schema.Codec<VisualConfigurationV1_8_0> =
  closed({
    $schema: Schema.Literal(
      "https://developer.microsoft.com/json-schemas/fabric/item/report/definition/visualConfiguration/1.8.0/schema.json",
    ),
    visualType: Schema.String,
    autoSelectVisualType: Schema.optionalKey(Schema.Boolean),
    query: Schema.optionalKey(Schema.suspend(() => QueryV1_8_0)),
    expansionStates: Schema.optionalKey(
      Schema.Array(Schema.suspend(() => ExpansionStateV1_5_0)),
    ),
    objects: Schema.optionalKey(
      Schema.suspend(() => DataViewObjectDefinitionsV1_3_0),
    ),
    visualContainerObjects: Schema.optionalKey(
      Schema.suspend(() => VisualContainerFormattingObjectsV1_8_0),
    ),
    syncGroup: Schema.optionalKey(Schema.suspend(() => VisualSyncGroup)),
    drillFilterOtherVisuals: Schema.optionalKey(Schema.Boolean),
  });

export const VisualConfigurationDefinitionsV1_8_0 = {
  Query: QueryV1_8_0,
  SortDefinition: SortDefinitionV1_5_0,
  QuerySort: QuerySortV1_5_0,
  SortDirection: SortDirection,
  VisualQueryOptions: VisualQueryOptions,
  ProjectionState: ProjectionStateV1_8_0,
  RoleProjection: RoleProjectionV1_5_0,
  RoleFieldParameter: RoleFieldParameterV1_8_0,
  ExpansionState: ExpansionStateV1_5_0,
  RootExpansionState: RootExpansionStateV1_5_0,
  NodeExpansionState: NodeExpansionStateV1_5_0,
  LevelExpansionState: LevelExpansionStateV1_5_0,
  AILevelInformation: AILevelInformation,
  AIDecompositionMethod: AIDecompositionMethod,
  VisualContainerFormattingObjects: VisualContainerFormattingObjectsV1_8_0,
  Title: Title,
  SubTitle: SubTitle,
  Divider: Divider,
  Spacing: Spacing,
  Background: Background,
  Padding: Padding,
  LockAspect: LockAspect,
  VisualContainerGeneralFormattingObjects:
    VisualContainerGeneralFormattingObjects,
  Border: Border,
  DropShadow: DropShadow,
  VisualLink: VisualLink,
  VisualTooltip: VisualTooltip,
  StylePreset: StylePreset,
  VisualHeader: VisualHeader,
  VisualHeaderTooltip: VisualHeaderTooltip,
  VisualSyncGroup: VisualSyncGroup,
} as const;

export const VisualConfigurationEmbeddedDefinitionsV1_8_0 = {
  Query: QueryV1_8_0,
  SortDefinition: SortDefinitionV1_5_0,
  QuerySort: QuerySortV1_5_0,
  SortDirection: SortDirection,
  VisualQueryOptions: VisualQueryOptions,
  ProjectionState: ProjectionStateV1_8_0,
  RoleProjection: RoleProjectionV1_5_0,
  RoleFieldParameter: RoleFieldParameterV1_8_0,
  ExpansionState: ExpansionStateV1_5_0,
  RootExpansionState: RootExpansionStateV1_5_0,
  NodeExpansionState: NodeExpansionStateV1_5_0,
  LevelExpansionState: LevelExpansionStateV1_5_0,
  AILevelInformation: AILevelInformation,
  AIDecompositionMethod: AIDecompositionMethod,
  VisualContainerFormattingObjects: VisualContainerFormattingObjectsV1_8_0,
  Title: Title,
  SubTitle: SubTitle,
  Divider: Divider,
  Spacing: Spacing,
  Background: Background,
  Padding: Padding,
  LockAspect: LockAspect,
  VisualContainerGeneralFormattingObjects:
    VisualContainerGeneralFormattingObjects,
  Border: Border,
  DropShadow: DropShadow,
  VisualLink: VisualLink,
  VisualTooltip: VisualTooltip,
  StylePreset: StylePreset,
  VisualHeader: VisualHeader,
  VisualHeaderTooltip: VisualHeaderTooltip,
  VisualSyncGroup: VisualSyncGroup,
} as const;

export {
  QueryV1_8_0 as VisualConfigurationQueryV1_8_0,
  SortDefinitionV1_5_0 as VisualConfigurationSortDefinitionV1_8_0,
  QuerySortV1_5_0 as VisualConfigurationQuerySortV1_8_0,
  SortDirection as VisualConfigurationSortDirectionV1_8_0,
  VisualQueryOptions as VisualConfigurationVisualQueryOptionsV1_8_0,
  ProjectionStateV1_8_0 as VisualConfigurationProjectionStateV1_8_0,
  RoleProjectionV1_5_0 as VisualConfigurationRoleProjectionV1_8_0,
  RoleFieldParameterV1_8_0 as VisualConfigurationRoleFieldParameterV1_8_0,
  ExpansionStateV1_5_0 as VisualConfigurationExpansionStateV1_8_0,
  RootExpansionStateV1_5_0 as VisualConfigurationRootExpansionStateV1_8_0,
  NodeExpansionStateV1_5_0 as VisualConfigurationNodeExpansionStateV1_8_0,
  LevelExpansionStateV1_5_0 as VisualConfigurationLevelExpansionStateV1_8_0,
  AILevelInformation as VisualConfigurationAILevelInformationV1_8_0,
  AIDecompositionMethod as VisualConfigurationAIDecompositionMethodV1_8_0,
  VisualContainerFormattingObjectsV1_8_0 as VisualConfigurationVisualContainerFormattingObjectsV1_8_0,
  VisualSyncGroup as VisualConfigurationVisualSyncGroupV1_8_0,
  QueryV1_8_0 as VisualConfigurationEmbeddedQueryV1_8_0,
  SortDefinitionV1_5_0 as VisualConfigurationEmbeddedSortDefinitionV1_8_0,
  QuerySortV1_5_0 as VisualConfigurationEmbeddedQuerySortV1_8_0,
  SortDirection as VisualConfigurationEmbeddedSortDirectionV1_8_0,
  VisualQueryOptions as VisualConfigurationEmbeddedVisualQueryOptionsV1_8_0,
  ProjectionStateV1_8_0 as VisualConfigurationEmbeddedProjectionStateV1_8_0,
  RoleProjectionV1_5_0 as VisualConfigurationEmbeddedRoleProjectionV1_8_0,
  RoleFieldParameterV1_8_0 as VisualConfigurationEmbeddedRoleFieldParameterV1_8_0,
  ExpansionStateV1_5_0 as VisualConfigurationEmbeddedExpansionStateV1_8_0,
  RootExpansionStateV1_5_0 as VisualConfigurationEmbeddedRootExpansionStateV1_8_0,
  NodeExpansionStateV1_5_0 as VisualConfigurationEmbeddedNodeExpansionStateV1_8_0,
  LevelExpansionStateV1_5_0 as VisualConfigurationEmbeddedLevelExpansionStateV1_8_0,
  AILevelInformation as VisualConfigurationEmbeddedAILevelInformationV1_8_0,
  AIDecompositionMethod as VisualConfigurationEmbeddedAIDecompositionMethodV1_8_0,
  VisualContainerFormattingObjectsV1_8_0 as VisualConfigurationEmbeddedVisualContainerFormattingObjectsV1_8_0,
  VisualSyncGroup as VisualConfigurationEmbeddedVisualSyncGroupV1_8_0,
  VisualConfigurationEmbeddedV1_8_0,
} from "./shared.js";

export {
  Title as VisualConfigurationTitleV1_8_0,
  SubTitle as VisualConfigurationSubTitleV1_8_0,
  Divider as VisualConfigurationDividerV1_8_0,
  Spacing as VisualConfigurationSpacingV1_8_0,
  Background as VisualConfigurationBackgroundV1_8_0,
  Padding as VisualConfigurationPaddingV1_8_0,
  LockAspect as VisualConfigurationLockAspectV1_8_0,
  VisualContainerGeneralFormattingObjects as VisualConfigurationVisualContainerGeneralFormattingObjectsV1_8_0,
  Border as VisualConfigurationBorderV1_8_0,
  DropShadow as VisualConfigurationDropShadowV1_8_0,
  VisualLink as VisualConfigurationVisualLinkV1_8_0,
  VisualTooltip as VisualConfigurationVisualTooltipV1_8_0,
  StylePreset as VisualConfigurationStylePresetV1_8_0,
  VisualHeader as VisualConfigurationVisualHeaderV1_8_0,
  VisualHeaderTooltip as VisualConfigurationVisualHeaderTooltipV1_8_0,
  Title as VisualConfigurationEmbeddedTitleV1_8_0,
  SubTitle as VisualConfigurationEmbeddedSubTitleV1_8_0,
  Divider as VisualConfigurationEmbeddedDividerV1_8_0,
  Spacing as VisualConfigurationEmbeddedSpacingV1_8_0,
  Background as VisualConfigurationEmbeddedBackgroundV1_8_0,
  Padding as VisualConfigurationEmbeddedPaddingV1_8_0,
  LockAspect as VisualConfigurationEmbeddedLockAspectV1_8_0,
  VisualContainerGeneralFormattingObjects as VisualConfigurationEmbeddedVisualContainerGeneralFormattingObjectsV1_8_0,
  Border as VisualConfigurationEmbeddedBorderV1_8_0,
  DropShadow as VisualConfigurationEmbeddedDropShadowV1_8_0,
  VisualLink as VisualConfigurationEmbeddedVisualLinkV1_8_0,
  VisualTooltip as VisualConfigurationEmbeddedVisualTooltipV1_8_0,
  StylePreset as VisualConfigurationEmbeddedStylePresetV1_8_0,
  VisualHeader as VisualConfigurationEmbeddedVisualHeaderV1_8_0,
  VisualHeaderTooltip as VisualConfigurationEmbeddedVisualHeaderTooltipV1_8_0,
} from "../shared.js";
