import { Schema } from "effect";
import { DataViewObjectDefinitionsV1_4_0 } from "../formatting-object-definitions/version-1.4.0.js";
import {
  Background,
  Border,
  closed,
  Divider,
  DropShadow,
  LockAspect,
  Padding,
  Spacing,
  StylePreset,
  SubTitle,
  Title,
  VisualContainerGeneralFormattingObjects,
  VisualHeader,
  VisualHeaderTooltip,
  VisualLink,
  VisualTooltip,
} from "../shared.js";
import {
  AIDecompositionMethod,
  AILevelInformation,
  ExpansionStateV2_0_0,
  LevelExpansionStateV2_0_0,
  NodeExpansionStateV2_0_0,
  ProjectionStateV2_0_0,
  QuerySortV2_0_0,
  QueryV2_0_0,
  RoleFieldParameterV2_0_0,
  RoleProjectionV2_0_0,
  RootExpansionStateV2_0_0,
  SortDefinitionV2_0_0,
  SortDirection,
  VisualContainerFormattingObjectsV2_0_0,
  VisualQueryOptions,
  VisualSyncGroup,
} from "./shared.js";

export type VisualConfigurationEmbeddedV2_1_0 = {
  readonly visualType: string;
  readonly autoSelectVisualType?: boolean;
  readonly query?: QueryV2_0_0;
  readonly expansionStates?: ReadonlyArray<ExpansionStateV2_0_0>;
  readonly objects?: DataViewObjectDefinitionsV1_4_0;
  readonly visualContainerObjects?: VisualContainerFormattingObjectsV2_0_0;
  readonly syncGroup?: VisualSyncGroup;
  readonly drillFilterOtherVisuals?: boolean;
};

export const VisualConfigurationEmbeddedV2_1_0: Schema.Codec<VisualConfigurationEmbeddedV2_1_0> =
  closed({
    visualType: Schema.String,
    autoSelectVisualType: Schema.optionalKey(Schema.Boolean),
    query: Schema.optionalKey(Schema.suspend(() => QueryV2_0_0)),
    expansionStates: Schema.optionalKey(
      Schema.Array(Schema.suspend(() => ExpansionStateV2_0_0)),
    ),
    objects: Schema.optionalKey(
      Schema.suspend(() => DataViewObjectDefinitionsV1_4_0),
    ),
    visualContainerObjects: Schema.optionalKey(
      Schema.suspend(() => VisualContainerFormattingObjectsV2_0_0),
    ),
    syncGroup: Schema.optionalKey(Schema.suspend(() => VisualSyncGroup)),
    drillFilterOtherVisuals: Schema.optionalKey(Schema.Boolean),
  });

export const VisualConfigurationDefinitionsV2_1_0 = {
  Query: QueryV2_0_0,
  SortDefinition: SortDefinitionV2_0_0,
  QuerySort: QuerySortV2_0_0,
  SortDirection: SortDirection,
  VisualQueryOptions: VisualQueryOptions,
  ProjectionState: ProjectionStateV2_0_0,
  RoleProjection: RoleProjectionV2_0_0,
  RoleFieldParameter: RoleFieldParameterV2_0_0,
  ExpansionState: ExpansionStateV2_0_0,
  RootExpansionState: RootExpansionStateV2_0_0,
  NodeExpansionState: NodeExpansionStateV2_0_0,
  LevelExpansionState: LevelExpansionStateV2_0_0,
  AILevelInformation: AILevelInformation,
  AIDecompositionMethod: AIDecompositionMethod,
  VisualContainerFormattingObjects: VisualContainerFormattingObjectsV2_0_0,
  Title: Title,
  SubTitle: SubTitle,
  Divider: Divider,
  Spacing: Spacing,
  Background: Background,
  Padding: Padding,
  LockAspect: LockAspect,
  VisualContainerGeneralFormattingObjects:
    VisualContainerGeneralFormattingObjects,
  Border: Border,
  DropShadow: DropShadow,
  VisualLink: VisualLink,
  VisualTooltip: VisualTooltip,
  StylePreset: StylePreset,
  VisualHeader: VisualHeader,
  VisualHeaderTooltip: VisualHeaderTooltip,
  VisualSyncGroup: VisualSyncGroup,
} as const;

export const VisualConfigurationEmbeddedDefinitionsV2_1_0 = {
  Query: QueryV2_0_0,
  SortDefinition: SortDefinitionV2_0_0,
  QuerySort: QuerySortV2_0_0,
  SortDirection: SortDirection,
  VisualQueryOptions: VisualQueryOptions,
  ProjectionState: ProjectionStateV2_0_0,
  RoleProjection: RoleProjectionV2_0_0,
  RoleFieldParameter: RoleFieldParameterV2_0_0,
  ExpansionState: ExpansionStateV2_0_0,
  RootExpansionState: RootExpansionStateV2_0_0,
  NodeExpansionState: NodeExpansionStateV2_0_0,
  LevelExpansionState: LevelExpansionStateV2_0_0,
  AILevelInformation: AILevelInformation,
  AIDecompositionMethod: AIDecompositionMethod,
  VisualContainerFormattingObjects: VisualContainerFormattingObjectsV2_0_0,
  Title: Title,
  SubTitle: SubTitle,
  Divider: Divider,
  Spacing: Spacing,
  Background: Background,
  Padding: Padding,
  LockAspect: LockAspect,
  VisualContainerGeneralFormattingObjects:
    VisualContainerGeneralFormattingObjects,
  Border: Border,
  DropShadow: DropShadow,
  VisualLink: VisualLink,
  VisualTooltip: VisualTooltip,
  StylePreset: StylePreset,
  VisualHeader: VisualHeader,
  VisualHeaderTooltip: VisualHeaderTooltip,
  VisualSyncGroup: VisualSyncGroup,
} as const;

export {
  QueryV2_0_0 as VisualConfigurationQueryV2_1_0,
  SortDefinitionV2_0_0 as VisualConfigurationSortDefinitionV2_1_0,
  QuerySortV2_0_0 as VisualConfigurationQuerySortV2_1_0,
  SortDirection as VisualConfigurationSortDirectionV2_1_0,
  VisualQueryOptions as VisualConfigurationVisualQueryOptionsV2_1_0,
  ProjectionStateV2_0_0 as VisualConfigurationProjectionStateV2_1_0,
  RoleProjectionV2_0_0 as VisualConfigurationRoleProjectionV2_1_0,
  RoleFieldParameterV2_0_0 as VisualConfigurationRoleFieldParameterV2_1_0,
  ExpansionStateV2_0_0 as VisualConfigurationExpansionStateV2_1_0,
  RootExpansionStateV2_0_0 as VisualConfigurationRootExpansionStateV2_1_0,
  NodeExpansionStateV2_0_0 as VisualConfigurationNodeExpansionStateV2_1_0,
  LevelExpansionStateV2_0_0 as VisualConfigurationLevelExpansionStateV2_1_0,
  AILevelInformation as VisualConfigurationAILevelInformationV2_1_0,
  AIDecompositionMethod as VisualConfigurationAIDecompositionMethodV2_1_0,
  VisualContainerFormattingObjectsV2_0_0 as VisualConfigurationVisualContainerFormattingObjectsV2_1_0,
  VisualSyncGroup as VisualConfigurationVisualSyncGroupV2_1_0,
  VisualConfigurationV2_0_0 as VisualConfigurationV2_1_0,
  QueryV2_0_0 as VisualConfigurationEmbeddedQueryV2_1_0,
  SortDefinitionV2_0_0 as VisualConfigurationEmbeddedSortDefinitionV2_1_0,
  QuerySortV2_0_0 as VisualConfigurationEmbeddedQuerySortV2_1_0,
  SortDirection as VisualConfigurationEmbeddedSortDirectionV2_1_0,
  VisualQueryOptions as VisualConfigurationEmbeddedVisualQueryOptionsV2_1_0,
  ProjectionStateV2_0_0 as VisualConfigurationEmbeddedProjectionStateV2_1_0,
  RoleProjectionV2_0_0 as VisualConfigurationEmbeddedRoleProjectionV2_1_0,
  RoleFieldParameterV2_0_0 as VisualConfigurationEmbeddedRoleFieldParameterV2_1_0,
  ExpansionStateV2_0_0 as VisualConfigurationEmbeddedExpansionStateV2_1_0,
  RootExpansionStateV2_0_0 as VisualConfigurationEmbeddedRootExpansionStateV2_1_0,
  NodeExpansionStateV2_0_0 as VisualConfigurationEmbeddedNodeExpansionStateV2_1_0,
  LevelExpansionStateV2_0_0 as VisualConfigurationEmbeddedLevelExpansionStateV2_1_0,
  AILevelInformation as VisualConfigurationEmbeddedAILevelInformationV2_1_0,
  AIDecompositionMethod as VisualConfigurationEmbeddedAIDecompositionMethodV2_1_0,
  VisualContainerFormattingObjectsV2_0_0 as VisualConfigurationEmbeddedVisualContainerFormattingObjectsV2_1_0,
  VisualSyncGroup as VisualConfigurationEmbeddedVisualSyncGroupV2_1_0,
} from "./shared.js";

export {
  Title as VisualConfigurationTitleV2_1_0,
  SubTitle as VisualConfigurationSubTitleV2_1_0,
  Divider as VisualConfigurationDividerV2_1_0,
  Spacing as VisualConfigurationSpacingV2_1_0,
  Background as VisualConfigurationBackgroundV2_1_0,
  Padding as VisualConfigurationPaddingV2_1_0,
  LockAspect as VisualConfigurationLockAspectV2_1_0,
  VisualContainerGeneralFormattingObjects as VisualConfigurationVisualContainerGeneralFormattingObjectsV2_1_0,
  Border as VisualConfigurationBorderV2_1_0,
  DropShadow as VisualConfigurationDropShadowV2_1_0,
  VisualLink as VisualConfigurationVisualLinkV2_1_0,
  VisualTooltip as VisualConfigurationVisualTooltipV2_1_0,
  StylePreset as VisualConfigurationStylePresetV2_1_0,
  VisualHeader as VisualConfigurationVisualHeaderV2_1_0,
  VisualHeaderTooltip as VisualConfigurationVisualHeaderTooltipV2_1_0,
  Title as VisualConfigurationEmbeddedTitleV2_1_0,
  SubTitle as VisualConfigurationEmbeddedSubTitleV2_1_0,
  Divider as VisualConfigurationEmbeddedDividerV2_1_0,
  Spacing as VisualConfigurationEmbeddedSpacingV2_1_0,
  Background as VisualConfigurationEmbeddedBackgroundV2_1_0,
  Padding as VisualConfigurationEmbeddedPaddingV2_1_0,
  LockAspect as VisualConfigurationEmbeddedLockAspectV2_1_0,
  VisualContainerGeneralFormattingObjects as VisualConfigurationEmbeddedVisualContainerGeneralFormattingObjectsV2_1_0,
  Border as VisualConfigurationEmbeddedBorderV2_1_0,
  DropShadow as VisualConfigurationEmbeddedDropShadowV2_1_0,
  VisualLink as VisualConfigurationEmbeddedVisualLinkV2_1_0,
  VisualTooltip as VisualConfigurationEmbeddedVisualTooltipV2_1_0,
  StylePreset as VisualConfigurationEmbeddedStylePresetV2_1_0,
  VisualHeader as VisualConfigurationEmbeddedVisualHeaderV2_1_0,
  VisualHeaderTooltip as VisualConfigurationEmbeddedVisualHeaderTooltipV2_1_0,
} from "../shared.js";
