import { Schema } from "effect";

import { DataViewObjectDefinitionsV1_2_0 } from "../formatting-object-definitions/version-1.2.0.js";
import {
  Background as SharedBackground,
  Border as SharedBorder,
  closed,
  Divider,
  DropShadow,
  LockAspect,
  Padding,
  Spacing,
  StylePreset,
  SubTitle,
  Title,
  VisualContainerGeneralFormattingObjects,
  VisualHeader as SharedVisualHeader,
  VisualHeaderTooltip,
  VisualLink as SharedVisualLink,
  VisualTooltip,
} from "../shared.js";
import {
  AIDecompositionMethod,
  AILevelInformation,
  ExpansionStateV1_5_0,
  LevelExpansionStateV1_5_0,
  NodeExpansionStateV1_5_0,
  ProjectionStateV1_5_0,
  QuerySortV1_5_0,
  QueryV1_5_0,
  RoleFieldParameterV1_5_0,
  RoleProjectionV1_5_0,
  RootExpansionStateV1_5_0,
  SortDefinitionV1_5_0,
  SortDirection as VisualConfigurationSortDirection,
  VisualContainerFormattingObjectsV1_5_0,
  VisualQueryOptions,
  VisualSyncGroup,
} from "./shared.js";

export type VisualConfigurationV1_5_0 = {
  readonly $schema: "https://developer.microsoft.com/json-schemas/fabric/item/report/definition/visualConfiguration/1.5.0/schema.json";
  readonly visualType: string;
  readonly autoSelectVisualType?: boolean;
  readonly query?: QueryV1_5_0;
  readonly expansionStates?: ReadonlyArray<ExpansionStateV1_5_0>;
  readonly objects?: DataViewObjectDefinitionsV1_2_0;
  readonly visualContainerObjects?: VisualContainerFormattingObjectsV1_5_0;
  readonly syncGroup?: VisualSyncGroup;
  readonly drillFilterOtherVisuals?: boolean;
};

export const VisualConfigurationV1_5_0: Schema.Codec<VisualConfigurationV1_5_0> =
  closed({
    $schema: Schema.Literal(
      "https://developer.microsoft.com/json-schemas/fabric/item/report/definition/visualConfiguration/1.5.0/schema.json",
    ),
    visualType: Schema.String,
    autoSelectVisualType: Schema.optionalKey(Schema.Boolean),
    query: Schema.optionalKey(Schema.suspend(() => QueryV1_5_0)),
    expansionStates: Schema.optionalKey(
      Schema.Array(Schema.suspend(() => ExpansionStateV1_5_0)),
    ),
    objects: Schema.optionalKey(
      Schema.suspend(() => DataViewObjectDefinitionsV1_2_0),
    ),
    visualContainerObjects: Schema.optionalKey(
      Schema.suspend(() => VisualContainerFormattingObjectsV1_5_0),
    ),
    syncGroup: Schema.optionalKey(Schema.suspend(() => VisualSyncGroup)),
    drillFilterOtherVisuals: Schema.optionalKey(Schema.Boolean),
  });

export const VisualConfigurationDefinitionsV1_5_0 = {
  Query: QueryV1_5_0,
  SortDefinition: SortDefinitionV1_5_0,
  QuerySort: QuerySortV1_5_0,
  SortDirection: VisualConfigurationSortDirection,
  VisualQueryOptions: VisualQueryOptions,
  ProjectionState: ProjectionStateV1_5_0,
  RoleProjection: RoleProjectionV1_5_0,
  RoleFieldParameter: RoleFieldParameterV1_5_0,
  ExpansionState: ExpansionStateV1_5_0,
  RootExpansionState: RootExpansionStateV1_5_0,
  NodeExpansionState: NodeExpansionStateV1_5_0,
  LevelExpansionState: LevelExpansionStateV1_5_0,
  AILevelInformation: AILevelInformation,
  AIDecompositionMethod: AIDecompositionMethod,
  VisualContainerFormattingObjects: VisualContainerFormattingObjectsV1_5_0,
  Title: Title,
  SubTitle: SubTitle,
  Divider: Divider,
  Spacing: Spacing,
  Background: SharedBackground,
  Padding: Padding,
  LockAspect: LockAspect,
  VisualContainerGeneralFormattingObjects:
    VisualContainerGeneralFormattingObjects,
  Border: SharedBorder,
  DropShadow: DropShadow,
  VisualLink: SharedVisualLink,
  VisualTooltip: VisualTooltip,
  StylePreset: StylePreset,
  VisualHeader: SharedVisualHeader,
  VisualHeaderTooltip: VisualHeaderTooltip,
  VisualSyncGroup: VisualSyncGroup,
} as const;

export const VisualConfigurationEmbeddedDefinitionsV1_5_0 = {
  Query: QueryV1_5_0,
  SortDefinition: SortDefinitionV1_5_0,
  QuerySort: QuerySortV1_5_0,
  SortDirection: VisualConfigurationSortDirection,
  VisualQueryOptions: VisualQueryOptions,
  ProjectionState: ProjectionStateV1_5_0,
  RoleProjection: RoleProjectionV1_5_0,
  RoleFieldParameter: RoleFieldParameterV1_5_0,
  ExpansionState: ExpansionStateV1_5_0,
  RootExpansionState: RootExpansionStateV1_5_0,
  NodeExpansionState: NodeExpansionStateV1_5_0,
  LevelExpansionState: LevelExpansionStateV1_5_0,
  AILevelInformation: AILevelInformation,
  AIDecompositionMethod: AIDecompositionMethod,
  VisualContainerFormattingObjects: VisualContainerFormattingObjectsV1_5_0,
  Title: Title,
  SubTitle: SubTitle,
  Divider: Divider,
  Spacing: Spacing,
  Background: SharedBackground,
  Padding: Padding,
  LockAspect: LockAspect,
  VisualContainerGeneralFormattingObjects:
    VisualContainerGeneralFormattingObjects,
  Border: SharedBorder,
  DropShadow: DropShadow,
  VisualLink: SharedVisualLink,
  VisualTooltip: VisualTooltip,
  StylePreset: StylePreset,
  VisualHeader: SharedVisualHeader,
  VisualHeaderTooltip: VisualHeaderTooltip,
  VisualSyncGroup: VisualSyncGroup,
} as const;

export {
  QueryV1_5_0 as VisualConfigurationQueryV1_5_0,
  SortDefinitionV1_5_0 as VisualConfigurationSortDefinitionV1_5_0,
  QuerySortV1_5_0 as VisualConfigurationQuerySortV1_5_0,
  SortDirection as VisualConfigurationSortDirectionV1_5_0,
  VisualQueryOptions as VisualConfigurationVisualQueryOptionsV1_5_0,
  ProjectionStateV1_5_0 as VisualConfigurationProjectionStateV1_5_0,
  RoleProjectionV1_5_0 as VisualConfigurationRoleProjectionV1_5_0,
  RoleFieldParameterV1_5_0 as VisualConfigurationRoleFieldParameterV1_5_0,
  ExpansionStateV1_5_0 as VisualConfigurationExpansionStateV1_5_0,
  RootExpansionStateV1_5_0 as VisualConfigurationRootExpansionStateV1_5_0,
  NodeExpansionStateV1_5_0 as VisualConfigurationNodeExpansionStateV1_5_0,
  LevelExpansionStateV1_5_0 as VisualConfigurationLevelExpansionStateV1_5_0,
  AILevelInformation as VisualConfigurationAILevelInformationV1_5_0,
  AIDecompositionMethod as VisualConfigurationAIDecompositionMethodV1_5_0,
  VisualContainerFormattingObjectsV1_5_0 as VisualConfigurationVisualContainerFormattingObjectsV1_5_0,
  VisualSyncGroup as VisualConfigurationVisualSyncGroupV1_5_0,
  QueryV1_5_0 as VisualConfigurationEmbeddedQueryV1_5_0,
  SortDefinitionV1_5_0 as VisualConfigurationEmbeddedSortDefinitionV1_5_0,
  QuerySortV1_5_0 as VisualConfigurationEmbeddedQuerySortV1_5_0,
  SortDirection as VisualConfigurationEmbeddedSortDirectionV1_5_0,
  VisualQueryOptions as VisualConfigurationEmbeddedVisualQueryOptionsV1_5_0,
  ProjectionStateV1_5_0 as VisualConfigurationEmbeddedProjectionStateV1_5_0,
  RoleProjectionV1_5_0 as VisualConfigurationEmbeddedRoleProjectionV1_5_0,
  RoleFieldParameterV1_5_0 as VisualConfigurationEmbeddedRoleFieldParameterV1_5_0,
  ExpansionStateV1_5_0 as VisualConfigurationEmbeddedExpansionStateV1_5_0,
  RootExpansionStateV1_5_0 as VisualConfigurationEmbeddedRootExpansionStateV1_5_0,
  NodeExpansionStateV1_5_0 as VisualConfigurationEmbeddedNodeExpansionStateV1_5_0,
  LevelExpansionStateV1_5_0 as VisualConfigurationEmbeddedLevelExpansionStateV1_5_0,
  AILevelInformation as VisualConfigurationEmbeddedAILevelInformationV1_5_0,
  AIDecompositionMethod as VisualConfigurationEmbeddedAIDecompositionMethodV1_5_0,
  VisualContainerFormattingObjectsV1_5_0 as VisualConfigurationEmbeddedVisualContainerFormattingObjectsV1_5_0,
  VisualSyncGroup as VisualConfigurationEmbeddedVisualSyncGroupV1_5_0,
  VisualConfigurationEmbeddedV1_5_0,
} from "./shared.js";

export {
  Title as VisualConfigurationTitleV1_5_0,
  SubTitle as VisualConfigurationSubTitleV1_5_0,
  Divider as VisualConfigurationDividerV1_5_0,
  Spacing as VisualConfigurationSpacingV1_5_0,
  Background as VisualConfigurationBackgroundV1_5_0,
  Padding as VisualConfigurationPaddingV1_5_0,
  LockAspect as VisualConfigurationLockAspectV1_5_0,
  VisualContainerGeneralFormattingObjects as VisualConfigurationVisualContainerGeneralFormattingObjectsV1_5_0,
  Border as VisualConfigurationBorderV1_5_0,
  DropShadow as VisualConfigurationDropShadowV1_5_0,
  VisualLink as VisualConfigurationVisualLinkV1_5_0,
  VisualTooltip as VisualConfigurationVisualTooltipV1_5_0,
  StylePreset as VisualConfigurationStylePresetV1_5_0,
  VisualHeader as VisualConfigurationVisualHeaderV1_5_0,
  VisualHeaderTooltip as VisualConfigurationVisualHeaderTooltipV1_5_0,
  Title as VisualConfigurationEmbeddedTitleV1_5_0,
  SubTitle as VisualConfigurationEmbeddedSubTitleV1_5_0,
  Divider as VisualConfigurationEmbeddedDividerV1_5_0,
  Spacing as VisualConfigurationEmbeddedSpacingV1_5_0,
  Background as VisualConfigurationEmbeddedBackgroundV1_5_0,
  Padding as VisualConfigurationEmbeddedPaddingV1_5_0,
  LockAspect as VisualConfigurationEmbeddedLockAspectV1_5_0,
  VisualContainerGeneralFormattingObjects as VisualConfigurationEmbeddedVisualContainerGeneralFormattingObjectsV1_5_0,
  Border as VisualConfigurationEmbeddedBorderV1_5_0,
  DropShadow as VisualConfigurationEmbeddedDropShadowV1_5_0,
  VisualLink as VisualConfigurationEmbeddedVisualLinkV1_5_0,
  VisualTooltip as VisualConfigurationEmbeddedVisualTooltipV1_5_0,
  StylePreset as VisualConfigurationEmbeddedStylePresetV1_5_0,
  VisualHeader as VisualConfigurationEmbeddedVisualHeaderV1_5_0,
  VisualHeaderTooltip as VisualConfigurationEmbeddedVisualHeaderTooltipV1_5_0,
} from "../shared.js";
