import {
  Background,
  Border,
  Divider,
  DropShadow,
  LockAspect,
  Padding,
  Spacing,
  StylePreset,
  SubTitle,
  Title,
  VisualContainerGeneralFormattingObjects,
  VisualHeader,
  VisualHeaderTooltip,
  VisualLink,
  VisualTooltip,
} from "../shared.js";
import {
  AIDecompositionMethod,
  AILevelInformation,
  ExpansionStateV1_5_0,
  ExpansionStateV2_0_0,
  LevelExpansionStateV1_5_0,
  LevelExpansionStateV2_0_0,
  NodeExpansionStateV1_5_0,
  NodeExpansionStateV2_0_0,
  ProjectionStateV1_8_0,
  ProjectionStateV2_0_0,
  QuerySortV1_5_0,
  QuerySortV2_0_0,
  QueryV1_8_0,
  QueryV2_0_0,
  RoleFieldParameterV1_8_0,
  RoleFieldParameterV2_0_0,
  RoleProjectionV1_5_0,
  RoleProjectionV2_0_0,
  RootExpansionStateV1_5_0,
  RootExpansionStateV2_0_0,
  SortDefinitionV1_5_0,
  SortDefinitionV2_0_0,
  SortDirection,
  VisualContainerFormattingObjectsV1_8_0,
  VisualContainerFormattingObjectsV2_0_0,
  VisualQueryOptions,
  VisualSyncGroup,
} from "./shared.js";

export const VisualConfigurationDefinitionsV2_0_0 = {
  Query: QueryV2_0_0,
  SortDefinition: SortDefinitionV2_0_0,
  QuerySort: QuerySortV2_0_0,
  SortDirection: SortDirection,
  VisualQueryOptions: VisualQueryOptions,
  ProjectionState: ProjectionStateV2_0_0,
  RoleProjection: RoleProjectionV2_0_0,
  RoleFieldParameter: RoleFieldParameterV2_0_0,
  ExpansionState: ExpansionStateV2_0_0,
  RootExpansionState: RootExpansionStateV2_0_0,
  NodeExpansionState: NodeExpansionStateV2_0_0,
  LevelExpansionState: LevelExpansionStateV2_0_0,
  AILevelInformation: AILevelInformation,
  AIDecompositionMethod: AIDecompositionMethod,
  VisualContainerFormattingObjects: VisualContainerFormattingObjectsV2_0_0,
  Title: Title,
  SubTitle: SubTitle,
  Divider: Divider,
  Spacing: Spacing,
  Background: Background,
  Padding: Padding,
  LockAspect: LockAspect,
  VisualContainerGeneralFormattingObjects:
    VisualContainerGeneralFormattingObjects,
  Border: Border,
  DropShadow: DropShadow,
  VisualLink: VisualLink,
  VisualTooltip: VisualTooltip,
  StylePreset: StylePreset,
  VisualHeader: VisualHeader,
  VisualHeaderTooltip: VisualHeaderTooltip,
  VisualSyncGroup: VisualSyncGroup,
} as const;

export const VisualConfigurationEmbeddedDefinitionsV2_0_0 = {
  Query: QueryV1_8_0,
  SortDefinition: SortDefinitionV1_5_0,
  QuerySort: QuerySortV1_5_0,
  SortDirection: SortDirection,
  VisualQueryOptions: VisualQueryOptions,
  ProjectionState: ProjectionStateV1_8_0,
  RoleProjection: RoleProjectionV1_5_0,
  RoleFieldParameter: RoleFieldParameterV1_8_0,
  ExpansionState: ExpansionStateV1_5_0,
  RootExpansionState: RootExpansionStateV1_5_0,
  NodeExpansionState: NodeExpansionStateV1_5_0,
  LevelExpansionState: LevelExpansionStateV1_5_0,
  AILevelInformation: AILevelInformation,
  AIDecompositionMethod: AIDecompositionMethod,
  VisualContainerFormattingObjects: VisualContainerFormattingObjectsV1_8_0,
  Title: Title,
  SubTitle: SubTitle,
  Divider: Divider,
  Spacing: Spacing,
  Background: Background,
  Padding: Padding,
  LockAspect: LockAspect,
  VisualContainerGeneralFormattingObjects:
    VisualContainerGeneralFormattingObjects,
  Border: Border,
  DropShadow: DropShadow,
  VisualLink: VisualLink,
  VisualTooltip: VisualTooltip,
  StylePreset: StylePreset,
  VisualHeader: VisualHeader,
  VisualHeaderTooltip: VisualHeaderTooltip,
  VisualSyncGroup: VisualSyncGroup,
} as const;

export {
  QueryV2_0_0 as VisualConfigurationQueryV2_0_0,
  SortDefinitionV2_0_0 as VisualConfigurationSortDefinitionV2_0_0,
  QuerySortV2_0_0 as VisualConfigurationQuerySortV2_0_0,
  SortDirection as VisualConfigurationSortDirectionV2_0_0,
  VisualQueryOptions as VisualConfigurationVisualQueryOptionsV2_0_0,
  ProjectionStateV2_0_0 as VisualConfigurationProjectionStateV2_0_0,
  RoleProjectionV2_0_0 as VisualConfigurationRoleProjectionV2_0_0,
  RoleFieldParameterV2_0_0 as VisualConfigurationRoleFieldParameterV2_0_0,
  ExpansionStateV2_0_0 as VisualConfigurationExpansionStateV2_0_0,
  RootExpansionStateV2_0_0 as VisualConfigurationRootExpansionStateV2_0_0,
  NodeExpansionStateV2_0_0 as VisualConfigurationNodeExpansionStateV2_0_0,
  LevelExpansionStateV2_0_0 as VisualConfigurationLevelExpansionStateV2_0_0,
  AILevelInformation as VisualConfigurationAILevelInformationV2_0_0,
  AIDecompositionMethod as VisualConfigurationAIDecompositionMethodV2_0_0,
  VisualContainerFormattingObjectsV2_0_0 as VisualConfigurationVisualContainerFormattingObjectsV2_0_0,
  VisualSyncGroup as VisualConfigurationVisualSyncGroupV2_0_0,
  VisualConfigurationV2_0_0,
  QueryV1_8_0 as VisualConfigurationEmbeddedQueryV2_0_0,
  SortDefinitionV1_5_0 as VisualConfigurationEmbeddedSortDefinitionV2_0_0,
  QuerySortV1_5_0 as VisualConfigurationEmbeddedQuerySortV2_0_0,
  SortDirection as VisualConfigurationEmbeddedSortDirectionV2_0_0,
  VisualQueryOptions as VisualConfigurationEmbeddedVisualQueryOptionsV2_0_0,
  ProjectionStateV1_8_0 as VisualConfigurationEmbeddedProjectionStateV2_0_0,
  RoleProjectionV1_5_0 as VisualConfigurationEmbeddedRoleProjectionV2_0_0,
  RoleFieldParameterV1_8_0 as VisualConfigurationEmbeddedRoleFieldParameterV2_0_0,
  ExpansionStateV1_5_0 as VisualConfigurationEmbeddedExpansionStateV2_0_0,
  RootExpansionStateV1_5_0 as VisualConfigurationEmbeddedRootExpansionStateV2_0_0,
  NodeExpansionStateV1_5_0 as VisualConfigurationEmbeddedNodeExpansionStateV2_0_0,
  LevelExpansionStateV1_5_0 as VisualConfigurationEmbeddedLevelExpansionStateV2_0_0,
  AILevelInformation as VisualConfigurationEmbeddedAILevelInformationV2_0_0,
  AIDecompositionMethod as VisualConfigurationEmbeddedAIDecompositionMethodV2_0_0,
  VisualContainerFormattingObjectsV1_8_0 as VisualConfigurationEmbeddedVisualContainerFormattingObjectsV2_0_0,
  VisualSyncGroup as VisualConfigurationEmbeddedVisualSyncGroupV2_0_0,
  VisualConfigurationEmbeddedV1_8_0 as VisualConfigurationEmbeddedV2_0_0,
} from "./shared.js";

export {
  Title as VisualConfigurationTitleV2_0_0,
  SubTitle as VisualConfigurationSubTitleV2_0_0,
  Divider as VisualConfigurationDividerV2_0_0,
  Spacing as VisualConfigurationSpacingV2_0_0,
  Background as VisualConfigurationBackgroundV2_0_0,
  Padding as VisualConfigurationPaddingV2_0_0,
  LockAspect as VisualConfigurationLockAspectV2_0_0,
  VisualContainerGeneralFormattingObjects as VisualConfigurationVisualContainerGeneralFormattingObjectsV2_0_0,
  Border as VisualConfigurationBorderV2_0_0,
  DropShadow as VisualConfigurationDropShadowV2_0_0,
  VisualLink as VisualConfigurationVisualLinkV2_0_0,
  VisualTooltip as VisualConfigurationVisualTooltipV2_0_0,
  StylePreset as VisualConfigurationStylePresetV2_0_0,
  VisualHeader as VisualConfigurationVisualHeaderV2_0_0,
  VisualHeaderTooltip as VisualConfigurationVisualHeaderTooltipV2_0_0,
  Title as VisualConfigurationEmbeddedTitleV2_0_0,
  SubTitle as VisualConfigurationEmbeddedSubTitleV2_0_0,
  Divider as VisualConfigurationEmbeddedDividerV2_0_0,
  Spacing as VisualConfigurationEmbeddedSpacingV2_0_0,
  Background as VisualConfigurationEmbeddedBackgroundV2_0_0,
  Padding as VisualConfigurationEmbeddedPaddingV2_0_0,
  LockAspect as VisualConfigurationEmbeddedLockAspectV2_0_0,
  VisualContainerGeneralFormattingObjects as VisualConfigurationEmbeddedVisualContainerGeneralFormattingObjectsV2_0_0,
  Border as VisualConfigurationEmbeddedBorderV2_0_0,
  DropShadow as VisualConfigurationEmbeddedDropShadowV2_0_0,
  VisualLink as VisualConfigurationEmbeddedVisualLinkV2_0_0,
  VisualTooltip as VisualConfigurationEmbeddedVisualTooltipV2_0_0,
  StylePreset as VisualConfigurationEmbeddedStylePresetV2_0_0,
  VisualHeader as VisualConfigurationEmbeddedVisualHeaderV2_0_0,
  VisualHeaderTooltip as VisualConfigurationEmbeddedVisualHeaderTooltipV2_0_0,
} from "../shared.js";
