export const descriptions = {
	Page: {
		description: "Defines a single report page.",
		fields: {
			$schema: "Defines the schema to use for an item.",
			name: "A unique identifier for the page across the whole report.",
			displayName: "A user facing name for this page.",
			displayOption: "Defines how the page is scaled.",
			height:
				"Height of the page (in pixels) - optional only for 'DeprecatedDynamic' option, required otherwise.",
			width:
				"Width of the page (in pixels) - optional only for 'DeprecatedDynamic' option, required otherwise.",
			filterConfig:
				"Filters that apply to all the visuals on this page - on top of the filters defined for the whole report.",
			pageBinding: "Additional metadata defined for how this page is used (tooltip, drillthrough, etc).",
			objects: "Defines the formatting for different objects on a page.",
			type: "Specific usage of this page (for example drillthrough).",
			visibility: "Defines when this page should be visible - by default it is always visible.",
			visualInteractions: [
				"Defines how data point selection on a specific visual flow (as filters) to other visuals on the page.",
				"By default it is up-to the visual to apply it either as a cross-highlight or as a filter.",
			].join("\n"),
			autoPageGenerationConfig:
				"Configuration that was used to automatically generate a page (for example using 'Auto create the report' option).",
			annotations: "Additional information to be saved (for example comments, readme, etc) for this page.",
			howCreated: "Source of creation of this page.",
		},
	},
	PageBinding: {
		fields: {
			name: "Name of this binding - unique across the report.",
			type: "Specific usage of this binding (for example drillthrough).",
			referenceScope: "What is the scope under which the binding applies.",
			parameters: "Additional parameters to apply when the binding is invoked.",
			acceptsFilterContext: "Should additional filter context flow when applying the binding.",
		},
	},
	BindingParameter: {
		fields: {
			name: "Name of the parameter - unique across the report.",
			boundFilter: "Name of the filter which this parameter affects.",
			asAggregation: "The parameter should be applied when the field of the filter is aggregated.",
			qnaSingleSelectRequired: "Exactly one instance value should be picked as a filter for this parameter.",
			fieldExpr: "Field expression for page binding",
		},
	},
	PageFormattingObjects: {},
	"PageFormattingObjects.*": {
		fields: {
			selector: [
				"Defines the scope at which to apply the formatting for this object.",
				"Can also define rules for matching highlighted values and how multiple definitions for the same property should be ordered.",
			].join("\n"),
			properties: "Describes the properties of the object to apply formatting changes to.",
		},
	},
	PageInformation: {},
	PageSize: {},
	Background: {},
	DisplayArea: {},
	OutspacePane: {},
	FilterCard: {},
	PageRefresh: {},
	PersonalizeVisual: {},
	VisualInteraction: {
		fields: {
			source: "Visual name that will be the source of user interaction (selecting data point for example).",
			target: "Visual name for the target of the interaction (selecting data point for example).",
			type: "How should the interaction flow from source to target visual (as highlights, as filter, none).",
		},
	},
	AutoPageGenerationConfig: {
		fields: {
			selectedFields: "Data fields to use for the auto page generation",
			visualContainerConfigurations: "Visuals already on the page previously generated by the auto-config",
			layout: "The specific layout chosen to render the auto-visuals",
		},
	},
	QuickExploreVisualContainerConfig: {
		fields: {
			name: "Name of the visual - matches the name property in visual.json files",
			fields: "Specific data fields used to build this visual from the full set of selected fields",
		},
	},
	QuickExploreLayoutContainer: {
		fields: {
			related: "A layout that has 1 hero visual and some related visuals",
			combination: [
				"Layout that generates visuals purely based on combination of fields",
				"Deprecated: Use related layout instead.",
			].join("\n"),
		},
	},
	QuickExploreRelatedLayout: {
		fields: {
			dataTableName: "If data table is shown, then the name of that visual",
		},
	},
	QuickExploreCombinationLayout: {
		fields: {
			dataTableName: "If data table is shown, then the name of that visual",
		},
	},
	Annotation: {
		fields: {
			name: "Unique name for the annotation.",
			value: "A value for this annotation.",
		},
	},
};
