import { Schema } from "effect";
import {
  ArithmeticOperatorKind,
  AxisGroupV1_1_0,
  AxisV1_1_0,
  EntitySourceV1_1_0,
  IncludeAllTypes,
  QueryAggregateFunction,
  QueryAggregationExpressionV1_1_0,
  QueryAnyValueExpression,
  QueryArithmeticExpressionV1_1_0,
  QueryBetweenExpressionV1_1_0,
  QueryBinaryExpressionV1_1_0,
  QueryCaseV1_1_0,
  QueryColumnExpressionV1_1_0,
  QueryComparisonExpressionV1_1_0,
  QueryComparisonKind,
  QueryConditionalExpressionV1_1_0,
  QueryDateAddExpressionV1_1_0,
  QueryDateSpanExpressionV1_1_0,
  QueryDefinitionV1_1_0,
  QueryDiscretizeExpressionV1_1_0,
  QueryExpressionContainerV1_1_0,
  QueryExpressionContentCacheV1_1_0,
  QueryFillRuleExpressionV1_1_0,
  QueryFilteredEvalExpressionV1_1_0,
  QueryFilterV1_1_0,
  QueryFloorExpressionV1_1_0,
  QueryGroupRefExpressionV1_1_0,
  QueryHierarchyExpressionV1_1_0,
  QueryHierarchyLevelExpressionV1_1_0,
  QueryInExpressionV1_1_0,
  QueryLiteralExpression,
  QueryMaxExpressionV1_1_0,
  QueryNativeColumnV1_1_0,
  QueryNativeMeasureV1_1_0,
  QueryNativeVisualCalcV1_0_0,
  QueryNotExpressionV1_1_0,
  QueryNowExpression,
  QueryPercentileExpressionV1_1_0,
  QueryPropertyVariationSourceExpressionV1_1_0,
  QueryResourcePackageItem,
  QueryRoleRefExpression,
  QueryScopedEvalExpressionV1_1_0,
  QuerySelectRefExpression,
  QuerySortClauseV1_1_0,
  QuerySourceRefExpression,
  QuerySparklineDataExpressionV1_1_0,
  QuerySubqueryExpressionV1_1_0,
  QuerySummaryValueRefExpression,
  QueryThemeDataColorExpression,
  QueryTransformInputV1_1_0,
  QueryTransformOutputRoleRefExpression,
  QueryTransformOutputV1_1_0,
  QueryTransformTableColumnV1_1_0,
  QueryTransformTableV1_1_0,
  QueryTransformV1_1_0,
  QueryVisualTopNExpression,
  StandaloneSourceRefExpression,
  TimeUnit,
} from "./shared.js";
import { closed } from "../shared.js";

export type FilterDefinitionV1_1_0 = {
  readonly Version?: 2;
  readonly From: ReadonlyArray<EntitySourceV1_1_0>;
  readonly Where: ReadonlyArray<QueryFilterV1_1_0>;
};

export const FilterDefinitionV1_1_0: Schema.Codec<FilterDefinitionV1_1_0> =
  closed({
    Version: Schema.optionalKey(Schema.Literal(2)),
    From: Schema.Array(Schema.suspend(() => EntitySourceV1_1_0)),
    Where: Schema.Array(Schema.suspend(() => QueryFilterV1_1_0)),
  });

export const SemanticQueryDefinitionsV1_1_0 = {
  FilterDefinition: FilterDefinitionV1_1_0,
  QueryFilter: QueryFilterV1_1_0,
  QueryExpressionContainer: QueryExpressionContainerV1_1_0,
  QueryVisualTopNExpression: QueryVisualTopNExpression,
  QueryNativeColumn: QueryNativeColumnV1_1_0,
  QueryExpressionContentCache: QueryExpressionContentCacheV1_1_0,
  QueryNativeMeasure: QueryNativeMeasureV1_1_0,
  QueryConditionalExpression: QueryConditionalExpressionV1_1_0,
  QueryCase: QueryCaseV1_1_0,
  QueryThemeDataColorExpression: QueryThemeDataColorExpression,
  QuerySelectRefExpression: QuerySelectRefExpression,
  QueryAllRolesRefExpression: QueryNowExpression,
  QuerySummaryValueRefExpression: QuerySummaryValueRefExpression,
  QueryRoleRefExpression: QueryRoleRefExpression,
  QueryResourcePackageItem: QueryResourcePackageItem,
  QueryGroupRefExpression: QueryGroupRefExpressionV1_1_0,
  QueryFillRuleExpression: QueryFillRuleExpressionV1_1_0,
  QueryNativeVisualCalc: QueryNativeVisualCalcV1_0_0,
  QuerySparklineDataExpression: QuerySparklineDataExpressionV1_1_0,
  QueryTransformOutputRoleRefExpression: QueryTransformOutputRoleRefExpression,
  QueryTransformTableRefExpression: QuerySourceRefExpression,
  QueryFilteredEvalExpression: QueryFilteredEvalExpressionV1_1_0,
  QueryScopedEvalExpression: QueryScopedEvalExpressionV1_1_0,
  QueryFloorExpression: QueryFloorExpressionV1_1_0,
  QueryArithmeticExpression: QueryArithmeticExpressionV1_1_0,
  ArithmeticOperatorKind: ArithmeticOperatorKind,
  QueryAnyValueExpression: QueryAnyValueExpression,
  QueryDefaultValueExpression: QueryNowExpression,
  QueryNowExpression: QueryNowExpression,
  QueryDateAddExpression: QueryDateAddExpressionV1_1_0,
  TimeUnit: TimeUnit,
  QueryDateSpanExpression: QueryDateSpanExpressionV1_1_0,
  QueryLiteralExpression: QueryLiteralExpression,
  QueryExistsExpression: QueryNotExpressionV1_1_0,
  QueryStartsWithExpression: QueryBinaryExpressionV1_1_0,
  QueryContainsExpression: QueryBinaryExpressionV1_1_0,
  QueryNotExpression: QueryNotExpressionV1_1_0,
  QueryComparisonExpression: QueryComparisonExpressionV1_1_0,
  QueryComparisonKind: QueryComparisonKind,
  QueryBinaryExpression: QueryBinaryExpressionV1_1_0,
  QueryInExpression: QueryInExpressionV1_1_0,
  QueryBetweenExpression: QueryBetweenExpressionV1_1_0,
  QueryDiscretizeExpression: QueryDiscretizeExpressionV1_1_0,
  QuerySubqueryExpression: QuerySubqueryExpressionV1_1_0,
  QueryDefinition: QueryDefinitionV1_1_0,
  QueryTransform: QueryTransformV1_1_0,
  QueryTransformOutput: QueryTransformOutputV1_1_0,
  QueryTransformTable: QueryTransformTableV1_1_0,
  QueryTransformTableColumn: QueryTransformTableColumnV1_1_0,
  QueryTransformInput: QueryTransformInputV1_1_0,
  Axis: AxisV1_1_0,
  AxisGroup: AxisGroupV1_1_0,
  QuerySortClause: QuerySortClauseV1_1_0,
  EntitySource: EntitySourceV1_1_0,
  QueryPropertyVariationSourceExpression:
    QueryPropertyVariationSourceExpressionV1_1_0,
  QueryHierarchyLevelExpression: QueryHierarchyLevelExpressionV1_1_0,
  QueryHierarchyExpression: QueryHierarchyExpressionV1_1_0,
  QueryPercentileExpression: QueryPercentileExpressionV1_1_0,
  QueryAggregationExpression: QueryAggregationExpressionV1_1_0,
  QueryAggregateFunction: QueryAggregateFunction,
  QueryMaxExpression: QueryMaxExpressionV1_1_0,
  IncludeAllTypes: IncludeAllTypes,
  QueryMinExpression: QueryMaxExpressionV1_1_0,
  QueryMeasureExpression: QueryColumnExpressionV1_1_0,
  QueryColumnExpression: QueryColumnExpressionV1_1_0,
  QuerySourceRefExpression: QuerySourceRefExpression,
  StandaloneSourceRefExpression: StandaloneSourceRefExpression,
} as const;

export {
  QueryFilterV1_1_0,
  QueryExpressionContainerV1_1_0,
  QueryVisualTopNExpression as QueryVisualTopNExpressionV1_1_0,
  QueryNativeColumnV1_1_0,
  QueryExpressionContentCacheV1_1_0,
  QueryNativeMeasureV1_1_0,
  QueryConditionalExpressionV1_1_0,
  QueryCaseV1_1_0,
  QueryThemeDataColorExpression as QueryThemeDataColorExpressionV1_1_0,
  QuerySelectRefExpression as QuerySelectRefExpressionV1_1_0,
  QueryNowExpression as QueryAllRolesRefExpressionV1_1_0,
  QuerySummaryValueRefExpression as QuerySummaryValueRefExpressionV1_1_0,
  QueryRoleRefExpression as QueryRoleRefExpressionV1_1_0,
  QueryResourcePackageItem as QueryResourcePackageItemV1_1_0,
  QueryGroupRefExpressionV1_1_0,
  QueryFillRuleExpressionV1_1_0,
  QueryNativeVisualCalcV1_0_0 as QueryNativeVisualCalcV1_1_0,
  QuerySparklineDataExpressionV1_1_0,
  QueryTransformOutputRoleRefExpression as QueryTransformOutputRoleRefExpressionV1_1_0,
  QuerySourceRefExpression as QueryTransformTableRefExpressionV1_1_0,
  QueryFilteredEvalExpressionV1_1_0,
  QueryScopedEvalExpressionV1_1_0,
  QueryFloorExpressionV1_1_0,
  QueryArithmeticExpressionV1_1_0,
  ArithmeticOperatorKind as ArithmeticOperatorKindV1_1_0,
  QueryAnyValueExpression as QueryAnyValueExpressionV1_1_0,
  QueryNowExpression as QueryDefaultValueExpressionV1_1_0,
  QueryNowExpression as QueryNowExpressionV1_1_0,
  QueryDateAddExpressionV1_1_0,
  TimeUnit as TimeUnitV1_1_0,
  QueryDateSpanExpressionV1_1_0,
  QueryLiteralExpression as QueryLiteralExpressionV1_1_0,
  QueryNotExpressionV1_1_0 as QueryExistsExpressionV1_1_0,
  QueryBinaryExpressionV1_1_0 as QueryStartsWithExpressionV1_1_0,
  QueryBinaryExpressionV1_1_0 as QueryContainsExpressionV1_1_0,
  QueryNotExpressionV1_1_0,
  QueryComparisonExpressionV1_1_0,
  QueryComparisonKind as QueryComparisonKindV1_1_0,
  QueryBinaryExpressionV1_1_0,
  QueryInExpressionV1_1_0,
  QueryBetweenExpressionV1_1_0,
  QueryDiscretizeExpressionV1_1_0,
  QuerySubqueryExpressionV1_1_0,
  QueryDefinitionV1_1_0,
  QueryTransformV1_1_0,
  QueryTransformOutputV1_1_0,
  QueryTransformTableV1_1_0,
  QueryTransformTableColumnV1_1_0,
  QueryTransformInputV1_1_0,
  AxisV1_1_0,
  AxisGroupV1_1_0,
  QuerySortClauseV1_1_0,
  EntitySourceV1_1_0,
  QueryPropertyVariationSourceExpressionV1_1_0,
  QueryHierarchyLevelExpressionV1_1_0,
  QueryHierarchyExpressionV1_1_0,
  QueryPercentileExpressionV1_1_0,
  QueryAggregationExpressionV1_1_0,
  QueryAggregateFunction as QueryAggregateFunctionV1_1_0,
  QueryMaxExpressionV1_1_0,
  IncludeAllTypes as IncludeAllTypesV1_1_0,
  QueryMaxExpressionV1_1_0 as QueryMinExpressionV1_1_0,
  QueryColumnExpressionV1_1_0 as QueryMeasureExpressionV1_1_0,
  QueryColumnExpressionV1_1_0,
  QuerySourceRefExpression as QuerySourceRefExpressionV1_1_0,
  StandaloneSourceRefExpression as StandaloneSourceRefExpressionV1_1_0,
  SemanticQuery as SemanticQueryV1_1_0,
} from "./shared.js";
