import { Schema } from "effect";
import {
  ArithmeticOperatorKind,
  AxisGroupV1_0_0,
  AxisV1_0_0,
  EntitySourceV1_0_0,
  IncludeAllTypes,
  QueryAggregateFunction,
  QueryAggregationExpressionV1_0_0,
  QueryAnyValueExpression,
  QueryArithmeticExpressionV1_0_0,
  QueryBetweenExpressionV1_0_0,
  QueryBinaryExpressionV1_0_0,
  QueryCaseV1_0_0,
  QueryColumnExpressionV1_0_0,
  QueryComparisonExpressionV1_0_0,
  QueryComparisonKind,
  QueryConditionalExpressionV1_0_0,
  QueryDateAddExpressionV1_0_0,
  QueryDateSpanExpressionV1_0_0,
  QueryDefinitionV1_0_0,
  QueryDiscretizeExpressionV1_0_0,
  QueryExpressionContainerV1_0_0,
  QueryExpressionContentCacheV1_0_0,
  QueryFillRuleExpressionV1_0_0,
  QueryFilteredEvalExpressionV1_0_0,
  QueryFilterV1_0_0,
  QueryFloorExpressionV1_0_0,
  QueryGroupRefExpressionV1_0_0,
  QueryHierarchyExpressionV1_0_0,
  QueryHierarchyLevelExpressionV1_0_0,
  QueryInExpressionV1_0_0,
  QueryLiteralExpression,
  QueryMaxExpressionV1_0_0,
  QueryNativeColumnV1_0_0,
  QueryNativeMeasureV1_0_0,
  QueryNativeVisualCalcV1_0_0,
  QueryNotExpressionV1_0_0,
  QueryNowExpression,
  QueryPercentileExpressionV1_0_0,
  QueryPropertyVariationSourceExpressionV1_0_0,
  QueryResourcePackageItem,
  QueryRoleRefExpression,
  QueryScopedEvalExpressionV1_0_0,
  QuerySelectRefExpression,
  QuerySortClauseV1_0_0,
  QuerySourceRefExpression,
  QuerySparklineDataExpressionV1_0_0,
  QuerySubqueryExpressionV1_0_0,
  QuerySummaryValueRefExpression,
  QueryThemeDataColorExpression,
  QueryTransformInputV1_0_0,
  QueryTransformOutputRoleRefExpression,
  QueryTransformOutputV1_0_0,
  QueryTransformTableColumnV1_0_0,
  QueryTransformTableV1_0_0,
  QueryTransformV1_0_0,
  StandaloneSourceRefExpression,
  TimeUnit,
} from "./shared.js";
import { closed } from "../shared.js";

export type FilterDefinitionV1_0_0 = {
  readonly Version?: 2;
  readonly From: ReadonlyArray<EntitySourceV1_0_0>;
  readonly Where: ReadonlyArray<QueryFilterV1_0_0>;
};

export const FilterDefinitionV1_0_0: Schema.Codec<FilterDefinitionV1_0_0> =
  closed({
    Version: Schema.optionalKey(Schema.Literal(2)),
    From: Schema.Array(Schema.suspend(() => EntitySourceV1_0_0)),
    Where: Schema.Array(Schema.suspend(() => QueryFilterV1_0_0)),
  });

export const SemanticQueryDefinitionsV1_0_0 = {
  FilterDefinition: FilterDefinitionV1_0_0,
  QueryFilter: QueryFilterV1_0_0,
  QueryExpressionContainer: QueryExpressionContainerV1_0_0,
  QueryNativeColumn: QueryNativeColumnV1_0_0,
  QueryExpressionContentCache: QueryExpressionContentCacheV1_0_0,
  QueryNativeMeasure: QueryNativeMeasureV1_0_0,
  QueryConditionalExpression: QueryConditionalExpressionV1_0_0,
  QueryCase: QueryCaseV1_0_0,
  QueryThemeDataColorExpression: QueryThemeDataColorExpression,
  QuerySelectRefExpression: QuerySelectRefExpression,
  QueryAllRolesRefExpression: QueryNowExpression,
  QuerySummaryValueRefExpression: QuerySummaryValueRefExpression,
  QueryRoleRefExpression: QueryRoleRefExpression,
  QueryResourcePackageItem: QueryResourcePackageItem,
  QueryGroupRefExpression: QueryGroupRefExpressionV1_0_0,
  QueryFillRuleExpression: QueryFillRuleExpressionV1_0_0,
  QueryNativeVisualCalc: QueryNativeVisualCalcV1_0_0,
  QuerySparklineDataExpression: QuerySparklineDataExpressionV1_0_0,
  QueryTransformOutputRoleRefExpression: QueryTransformOutputRoleRefExpression,
  QueryTransformTableRefExpression: QuerySourceRefExpression,
  QueryFilteredEvalExpression: QueryFilteredEvalExpressionV1_0_0,
  QueryScopedEvalExpression: QueryScopedEvalExpressionV1_0_0,
  QueryFloorExpression: QueryFloorExpressionV1_0_0,
  QueryArithmeticExpression: QueryArithmeticExpressionV1_0_0,
  ArithmeticOperatorKind: ArithmeticOperatorKind,
  QueryAnyValueExpression: QueryAnyValueExpression,
  QueryDefaultValueExpression: QueryNowExpression,
  QueryNowExpression: QueryNowExpression,
  QueryDateAddExpression: QueryDateAddExpressionV1_0_0,
  TimeUnit: TimeUnit,
  QueryDateSpanExpression: QueryDateSpanExpressionV1_0_0,
  QueryLiteralExpression: QueryLiteralExpression,
  QueryExistsExpression: QueryNotExpressionV1_0_0,
  QueryStartsWithExpression: QueryBinaryExpressionV1_0_0,
  QueryContainsExpression: QueryBinaryExpressionV1_0_0,
  QueryNotExpression: QueryNotExpressionV1_0_0,
  QueryComparisonExpression: QueryComparisonExpressionV1_0_0,
  QueryComparisonKind: QueryComparisonKind,
  QueryBinaryExpression: QueryBinaryExpressionV1_0_0,
  QueryInExpression: QueryInExpressionV1_0_0,
  QueryBetweenExpression: QueryBetweenExpressionV1_0_0,
  QueryDiscretizeExpression: QueryDiscretizeExpressionV1_0_0,
  QuerySubqueryExpression: QuerySubqueryExpressionV1_0_0,
  QueryDefinition: QueryDefinitionV1_0_0,
  QueryTransform: QueryTransformV1_0_0,
  QueryTransformOutput: QueryTransformOutputV1_0_0,
  QueryTransformTable: QueryTransformTableV1_0_0,
  QueryTransformTableColumn: QueryTransformTableColumnV1_0_0,
  QueryTransformInput: QueryTransformInputV1_0_0,
  Axis: AxisV1_0_0,
  AxisGroup: AxisGroupV1_0_0,
  QuerySortClause: QuerySortClauseV1_0_0,
  EntitySource: EntitySourceV1_0_0,
  QueryPropertyVariationSourceExpression:
    QueryPropertyVariationSourceExpressionV1_0_0,
  QueryHierarchyLevelExpression: QueryHierarchyLevelExpressionV1_0_0,
  QueryHierarchyExpression: QueryHierarchyExpressionV1_0_0,
  QueryPercentileExpression: QueryPercentileExpressionV1_0_0,
  QueryAggregationExpression: QueryAggregationExpressionV1_0_0,
  QueryAggregateFunction: QueryAggregateFunction,
  QueryMaxExpression: QueryMaxExpressionV1_0_0,
  IncludeAllTypes: IncludeAllTypes,
  QueryMinExpression: QueryMaxExpressionV1_0_0,
  QueryMeasureExpression: QueryColumnExpressionV1_0_0,
  QueryColumnExpression: QueryColumnExpressionV1_0_0,
  QuerySourceRefExpression: QuerySourceRefExpression,
  StandaloneSourceRefExpression: StandaloneSourceRefExpression,
} as const;

export {
  QueryFilterV1_0_0,
  QueryExpressionContainerV1_0_0,
  QueryNativeColumnV1_0_0,
  QueryExpressionContentCacheV1_0_0,
  QueryNativeMeasureV1_0_0,
  QueryConditionalExpressionV1_0_0,
  QueryCaseV1_0_0,
  QueryThemeDataColorExpression as QueryThemeDataColorExpressionV1_0_0,
  QuerySelectRefExpression as QuerySelectRefExpressionV1_0_0,
  QueryNowExpression as QueryAllRolesRefExpressionV1_0_0,
  QuerySummaryValueRefExpression as QuerySummaryValueRefExpressionV1_0_0,
  QueryRoleRefExpression as QueryRoleRefExpressionV1_0_0,
  QueryResourcePackageItem as QueryResourcePackageItemV1_0_0,
  QueryGroupRefExpressionV1_0_0,
  QueryFillRuleExpressionV1_0_0,
  QueryNativeVisualCalcV1_0_0,
  QuerySparklineDataExpressionV1_0_0,
  QueryTransformOutputRoleRefExpression as QueryTransformOutputRoleRefExpressionV1_0_0,
  QuerySourceRefExpression as QueryTransformTableRefExpressionV1_0_0,
  QueryFilteredEvalExpressionV1_0_0,
  QueryScopedEvalExpressionV1_0_0,
  QueryFloorExpressionV1_0_0,
  QueryArithmeticExpressionV1_0_0,
  ArithmeticOperatorKind as ArithmeticOperatorKindV1_0_0,
  QueryAnyValueExpression as QueryAnyValueExpressionV1_0_0,
  QueryNowExpression as QueryDefaultValueExpressionV1_0_0,
  QueryNowExpression as QueryNowExpressionV1_0_0,
  QueryDateAddExpressionV1_0_0,
  TimeUnit as TimeUnitV1_0_0,
  QueryDateSpanExpressionV1_0_0,
  QueryLiteralExpression as QueryLiteralExpressionV1_0_0,
  QueryNotExpressionV1_0_0 as QueryExistsExpressionV1_0_0,
  QueryBinaryExpressionV1_0_0 as QueryStartsWithExpressionV1_0_0,
  QueryBinaryExpressionV1_0_0 as QueryContainsExpressionV1_0_0,
  QueryNotExpressionV1_0_0,
  QueryComparisonExpressionV1_0_0,
  QueryComparisonKind as QueryComparisonKindV1_0_0,
  QueryBinaryExpressionV1_0_0,
  QueryInExpressionV1_0_0,
  QueryBetweenExpressionV1_0_0,
  QueryDiscretizeExpressionV1_0_0,
  QuerySubqueryExpressionV1_0_0,
  QueryDefinitionV1_0_0,
  QueryTransformV1_0_0,
  QueryTransformOutputV1_0_0,
  QueryTransformTableV1_0_0,
  QueryTransformTableColumnV1_0_0,
  QueryTransformInputV1_0_0,
  AxisV1_0_0,
  AxisGroupV1_0_0,
  QuerySortClauseV1_0_0,
  EntitySourceV1_0_0,
  QueryPropertyVariationSourceExpressionV1_0_0,
  QueryHierarchyLevelExpressionV1_0_0,
  QueryHierarchyExpressionV1_0_0,
  QueryPercentileExpressionV1_0_0,
  QueryAggregationExpressionV1_0_0,
  QueryAggregateFunction as QueryAggregateFunctionV1_0_0,
  QueryMaxExpressionV1_0_0,
  IncludeAllTypes as IncludeAllTypesV1_0_0,
  QueryMaxExpressionV1_0_0 as QueryMinExpressionV1_0_0,
  QueryColumnExpressionV1_0_0 as QueryMeasureExpressionV1_0_0,
  QueryColumnExpressionV1_0_0,
  QuerySourceRefExpression as QuerySourceRefExpressionV1_0_0,
  StandaloneSourceRefExpression as StandaloneSourceRefExpressionV1_0_0,
  SemanticQuery as SemanticQueryV1_0_0,
} from "./shared.js";
