import { Schema } from "effect";
import {
  ArithmeticOperatorKind,
  AxisGroupV1_4_0,
  AxisV1_4_0,
  EntitySourceV1_4_0,
  IncludeAllTypes,
  QueryAggregateFunction,
  QueryAggregationExpressionV1_4_0,
  QueryAnyValueExpression,
  QueryArithmeticExpressionV1_4_0,
  QueryBetweenExpressionV1_4_0,
  QueryBinaryExpressionV1_4_0,
  QueryCaseV1_4_0,
  QueryColumnExpressionV1_4_0,
  QueryComparisonExpressionV1_4_0,
  QueryComparisonKind,
  QueryConditionalExpressionV1_4_0,
  QueryCustomTotalMetadata,
  QueryDateAddExpressionV1_4_0,
  QueryDateSpanExpressionV1_4_0,
  QueryDefinitionV1_4_0,
  QueryDiscretizeExpressionV1_4_0,
  QueryExpressionContainerV1_4_0,
  QueryExpressionContentCacheV1_4_0,
  QueryFillRuleExpressionV1_4_0,
  QueryFilteredEvalExpressionV1_4_0,
  QueryFilterV1_4_0,
  QueryFloorExpressionV1_4_0,
  QueryGroupRefExpressionV1_4_0,
  QueryHierarchyExpressionV1_4_0,
  QueryHierarchyLevelExpressionV1_4_0,
  QueryInExpressionV1_4_0,
  QueryLiteralExpression,
  QueryMaxExpressionV1_4_0,
  QueryNativeColumnV1_4_0,
  QueryNativeMeasureV1_4_0,
  QueryNativeVisualCalcV1_2_0,
  QueryNotExpressionV1_4_0,
  QueryNowExpression,
  QueryPercentileExpressionV1_4_0,
  QueryPropertyVariationSourceExpressionV1_4_0,
  QueryResourcePackageItem,
  QueryRoleRefExpression,
  QueryScopedEvalExpressionV1_4_0,
  QuerySelectRefExpression,
  QuerySortClauseV1_4_0,
  QuerySourceRefExpression,
  QuerySparklineDataExpressionV1_4_0,
  QuerySubqueryExpressionV1_4_0,
  QuerySummaryValueRefExpression,
  QueryThemeDataColorExpression,
  QueryTransformInputV1_4_0,
  QueryTransformOutputRoleRefExpression,
  QueryTransformOutputV1_4_0,
  QueryTransformTableColumnV1_4_0,
  QueryTransformTableV1_4_0,
  QueryTransformV1_4_0,
  QueryVisualTopNExpression,
  SortDirection,
  StandaloneSourceRefExpression,
  TimeUnit,
} from "./shared.js";
import { closed } from "../shared.js";

export type FilterDefinitionV1_4_0 = {
  readonly Version?: 2;
  readonly From: ReadonlyArray<EntitySourceV1_4_0>;
  readonly Where: ReadonlyArray<QueryFilterV1_4_0>;
};

export const FilterDefinitionV1_4_0: Schema.Codec<FilterDefinitionV1_4_0> =
  closed({
    Version: Schema.optionalKey(Schema.Literal(2)),
    From: Schema.Array(Schema.suspend(() => EntitySourceV1_4_0)),
    Where: Schema.Array(Schema.suspend(() => QueryFilterV1_4_0)),
  });

export const SemanticQueryDefinitionsV1_4_0 = {
  FilterDefinition: FilterDefinitionV1_4_0,
  QueryFilter: QueryFilterV1_4_0,
  QueryExpressionContainer: QueryExpressionContainerV1_4_0,
  QueryVisualTopNExpression: QueryVisualTopNExpression,
  QueryNativeColumn: QueryNativeColumnV1_4_0,
  QueryExpressionContentCache: QueryExpressionContentCacheV1_4_0,
  QueryNativeMeasure: QueryNativeMeasureV1_4_0,
  QueryConditionalExpression: QueryConditionalExpressionV1_4_0,
  QueryCase: QueryCaseV1_4_0,
  QueryThemeDataColorExpression: QueryThemeDataColorExpression,
  QuerySelectRefExpression: QuerySelectRefExpression,
  QueryAllRolesRefExpression: QueryNowExpression,
  QuerySummaryValueRefExpression: QuerySummaryValueRefExpression,
  QueryRoleRefExpression: QueryRoleRefExpression,
  QueryResourcePackageItem: QueryResourcePackageItem,
  QueryGroupRefExpression: QueryGroupRefExpressionV1_4_0,
  QueryFillRuleExpression: QueryFillRuleExpressionV1_4_0,
  QueryNativeVisualCalc: QueryNativeVisualCalcV1_2_0,
  QuerySparklineDataExpression: QuerySparklineDataExpressionV1_4_0,
  QueryTransformOutputRoleRefExpression: QueryTransformOutputRoleRefExpression,
  QueryTransformTableRefExpression: QuerySourceRefExpression,
  QueryFilteredEvalExpression: QueryFilteredEvalExpressionV1_4_0,
  QueryScopedEvalExpression: QueryScopedEvalExpressionV1_4_0,
  QueryFloorExpression: QueryFloorExpressionV1_4_0,
  QueryArithmeticExpression: QueryArithmeticExpressionV1_4_0,
  ArithmeticOperatorKind: ArithmeticOperatorKind,
  QueryAnyValueExpression: QueryAnyValueExpression,
  QueryDefaultValueExpression: QueryNowExpression,
  QueryNowExpression: QueryNowExpression,
  QueryDateAddExpression: QueryDateAddExpressionV1_4_0,
  TimeUnit: TimeUnit,
  QueryDateSpanExpression: QueryDateSpanExpressionV1_4_0,
  QueryLiteralExpression: QueryLiteralExpression,
  QueryExistsExpression: QueryNotExpressionV1_4_0,
  QueryStartsWithExpression: QueryBinaryExpressionV1_4_0,
  QueryContainsExpression: QueryBinaryExpressionV1_4_0,
  QueryNotExpression: QueryNotExpressionV1_4_0,
  QueryComparisonExpression: QueryComparisonExpressionV1_4_0,
  QueryComparisonKind: QueryComparisonKind,
  QueryBinaryExpression: QueryBinaryExpressionV1_4_0,
  QueryInExpression: QueryInExpressionV1_4_0,
  QueryBetweenExpression: QueryBetweenExpressionV1_4_0,
  QueryDiscretizeExpression: QueryDiscretizeExpressionV1_4_0,
  QuerySubqueryExpression: QuerySubqueryExpressionV1_4_0,
  QueryDefinition: QueryDefinitionV1_4_0,
  QueryTransform: QueryTransformV1_4_0,
  QueryTransformOutput: QueryTransformOutputV1_4_0,
  QueryTransformTable: QueryTransformTableV1_4_0,
  QueryTransformTableColumn: QueryTransformTableColumnV1_4_0,
  QueryTransformInput: QueryTransformInputV1_4_0,
  Axis: AxisV1_4_0,
  AxisGroup: AxisGroupV1_4_0,
  QuerySortClause: QuerySortClauseV1_4_0,
  SortDirection: SortDirection,
  EntitySource: EntitySourceV1_4_0,
  QueryPropertyVariationSourceExpression:
    QueryPropertyVariationSourceExpressionV1_4_0,
  QueryHierarchyLevelExpression: QueryHierarchyLevelExpressionV1_4_0,
  QueryHierarchyExpression: QueryHierarchyExpressionV1_4_0,
  QueryPercentileExpression: QueryPercentileExpressionV1_4_0,
  QueryAggregationExpression: QueryAggregationExpressionV1_4_0,
  QueryAggregateFunction: QueryAggregateFunction,
  QueryMaxExpression: QueryMaxExpressionV1_4_0,
  IncludeAllTypes: IncludeAllTypes,
  QueryMinExpression: QueryMaxExpressionV1_4_0,
  QueryMeasureExpression: QueryColumnExpressionV1_4_0,
  QueryColumnExpression: QueryColumnExpressionV1_4_0,
  QuerySourceRefExpression: QuerySourceRefExpression,
  StandaloneSourceRefExpression: StandaloneSourceRefExpression,
  QueryCustomTotalMetadata: QueryCustomTotalMetadata,
} as const;

export {
  QueryFilterV1_4_0,
  QueryExpressionContainerV1_4_0,
  QueryVisualTopNExpression as QueryVisualTopNExpressionV1_4_0,
  QueryNativeColumnV1_4_0,
  QueryExpressionContentCacheV1_4_0,
  QueryNativeMeasureV1_4_0,
  QueryConditionalExpressionV1_4_0,
  QueryCaseV1_4_0,
  QueryThemeDataColorExpression as QueryThemeDataColorExpressionV1_4_0,
  QuerySelectRefExpression as QuerySelectRefExpressionV1_4_0,
  QueryNowExpression as QueryAllRolesRefExpressionV1_4_0,
  QuerySummaryValueRefExpression as QuerySummaryValueRefExpressionV1_4_0,
  QueryRoleRefExpression as QueryRoleRefExpressionV1_4_0,
  QueryResourcePackageItem as QueryResourcePackageItemV1_4_0,
  QueryGroupRefExpressionV1_4_0,
  QueryFillRuleExpressionV1_4_0,
  QueryNativeVisualCalcV1_2_0 as QueryNativeVisualCalcV1_4_0,
  QuerySparklineDataExpressionV1_4_0,
  QueryTransformOutputRoleRefExpression as QueryTransformOutputRoleRefExpressionV1_4_0,
  QuerySourceRefExpression as QueryTransformTableRefExpressionV1_4_0,
  QueryFilteredEvalExpressionV1_4_0,
  QueryScopedEvalExpressionV1_4_0,
  QueryFloorExpressionV1_4_0,
  QueryArithmeticExpressionV1_4_0,
  ArithmeticOperatorKind as ArithmeticOperatorKindV1_4_0,
  QueryAnyValueExpression as QueryAnyValueExpressionV1_4_0,
  QueryNowExpression as QueryDefaultValueExpressionV1_4_0,
  QueryNowExpression as QueryNowExpressionV1_4_0,
  QueryDateAddExpressionV1_4_0,
  TimeUnit as TimeUnitV1_4_0,
  QueryDateSpanExpressionV1_4_0,
  QueryLiteralExpression as QueryLiteralExpressionV1_4_0,
  QueryNotExpressionV1_4_0 as QueryExistsExpressionV1_4_0,
  QueryBinaryExpressionV1_4_0 as QueryStartsWithExpressionV1_4_0,
  QueryBinaryExpressionV1_4_0 as QueryContainsExpressionV1_4_0,
  QueryNotExpressionV1_4_0,
  QueryComparisonExpressionV1_4_0,
  QueryComparisonKind as QueryComparisonKindV1_4_0,
  QueryBinaryExpressionV1_4_0,
  QueryInExpressionV1_4_0,
  QueryBetweenExpressionV1_4_0,
  QueryDiscretizeExpressionV1_4_0,
  QuerySubqueryExpressionV1_4_0,
  QueryDefinitionV1_4_0,
  QueryTransformV1_4_0,
  QueryTransformOutputV1_4_0,
  QueryTransformTableV1_4_0,
  QueryTransformTableColumnV1_4_0,
  QueryTransformInputV1_4_0,
  AxisV1_4_0,
  AxisGroupV1_4_0,
  QuerySortClauseV1_4_0,
  SortDirection as SortDirectionV1_4_0,
  EntitySourceV1_4_0,
  QueryPropertyVariationSourceExpressionV1_4_0,
  QueryHierarchyLevelExpressionV1_4_0,
  QueryHierarchyExpressionV1_4_0,
  QueryPercentileExpressionV1_4_0,
  QueryAggregationExpressionV1_4_0,
  QueryAggregateFunction as QueryAggregateFunctionV1_4_0,
  QueryMaxExpressionV1_4_0,
  IncludeAllTypes as IncludeAllTypesV1_4_0,
  QueryMaxExpressionV1_4_0 as QueryMinExpressionV1_4_0,
  QueryColumnExpressionV1_4_0 as QueryMeasureExpressionV1_4_0,
  QueryColumnExpressionV1_4_0,
  QuerySourceRefExpression as QuerySourceRefExpressionV1_4_0,
  StandaloneSourceRefExpression as StandaloneSourceRefExpressionV1_4_0,
  QueryCustomTotalMetadata as QueryCustomTotalMetadataV1_4_0,
  SemanticQuery as SemanticQueryV1_4_0,
} from "./shared.js";
