import {
  ArithmeticOperatorKindV1_0_0,
  AxisGroupV1_1_0,
  AxisV1_1_0,
  EntitySourceV1_1_0,
  FilterDefinitionV1_1_0,
  IncludeAllTypesV1_0_0,
  QueryAggregateFunctionV1_0_0,
  QueryAggregationExpressionV1_1_0,
  QueryAllRolesRefExpressionV1_0_0,
  QueryAnyValueExpressionV1_0_0,
  QueryArithmeticExpressionV1_1_0,
  QueryBetweenExpressionV1_1_0,
  QueryBinaryExpressionV1_1_0,
  QueryCaseV1_1_0,
  QueryColumnExpressionV1_1_0,
  QueryComparisonExpressionV1_1_0,
  QueryComparisonKindV1_0_0,
  QueryConditionalExpressionV1_1_0,
  QueryContainsExpressionV1_1_0,
  QueryDateAddExpressionV1_1_0,
  QueryDateSpanExpressionV1_1_0,
  QueryDefaultValueExpressionV1_0_0,
  QueryDefinitionV1_1_0,
  QueryDiscretizeExpressionV1_1_0,
  QueryExistsExpressionV1_1_0,
  QueryExpressionContainerV1_1_0,
  QueryExpressionContentCacheV1_1_0,
  QueryFillRuleExpressionV1_1_0,
  QueryFilterV1_1_0,
  QueryFilteredEvalExpressionV1_1_0,
  QueryFloorExpressionV1_1_0,
  QueryGroupRefExpressionV1_1_0,
  QueryHierarchyExpressionV1_1_0,
  QueryHierarchyLevelExpressionV1_1_0,
  QueryInExpressionV1_1_0,
  QueryLiteralExpressionV1_0_0,
  QueryMaxExpressionV1_1_0,
  QueryMeasureExpressionV1_1_0,
  QueryMinExpressionV1_1_0,
  QueryNativeColumnV1_1_0,
  QueryNativeMeasureV1_1_0,
  QueryNativeVisualCalcV1_0_0,
  QueryNotExpressionV1_1_0,
  QueryNowExpressionV1_0_0,
  QueryPercentileExpressionV1_1_0,
  QueryPropertyVariationSourceExpressionV1_1_0,
  QueryResourcePackageItemV1_0_0,
  QueryRoleRefExpressionV1_0_0,
  QueryScopedEvalExpressionV1_1_0,
  QuerySelectRefExpressionV1_0_0,
  QuerySortClauseV1_1_0,
  QuerySourceRefExpressionV1_0_0,
  QuerySparklineDataExpressionV1_1_0,
  QueryStartsWithExpressionV1_1_0,
  QuerySubqueryExpressionV1_1_0,
  QuerySummaryValueRefExpressionV1_0_0,
  QueryThemeDataColorExpressionV1_0_0,
  QueryTransformInputV1_1_0,
  QueryTransformOutputRoleRefExpressionV1_0_0,
  QueryTransformOutputV1_1_0,
  QueryTransformTableColumnV1_1_0,
  QueryTransformTableRefExpressionV1_0_0,
  QueryTransformTableV1_1_0,
  QueryTransformV1_1_0,
  QueryVisualTopNExpressionV1_1_0,
  StandaloneSourceRefExpressionV1_0_0,
  TimeUnitV1_0_0,
} from "./shared.js";

export const SemanticQueryDefinitionsV1_1_0 = {
  FilterDefinition: FilterDefinitionV1_1_0,
  QueryFilter: QueryFilterV1_1_0,
  QueryExpressionContainer: QueryExpressionContainerV1_1_0,
  QueryVisualTopNExpression: QueryVisualTopNExpressionV1_1_0,
  QueryNativeColumn: QueryNativeColumnV1_1_0,
  QueryExpressionContentCache: QueryExpressionContentCacheV1_1_0,
  QueryNativeMeasure: QueryNativeMeasureV1_1_0,
  QueryConditionalExpression: QueryConditionalExpressionV1_1_0,
  QueryCase: QueryCaseV1_1_0,
  QueryThemeDataColorExpression: QueryThemeDataColorExpressionV1_0_0,
  QuerySelectRefExpression: QuerySelectRefExpressionV1_0_0,
  QueryAllRolesRefExpression: QueryAllRolesRefExpressionV1_0_0,
  QuerySummaryValueRefExpression: QuerySummaryValueRefExpressionV1_0_0,
  QueryRoleRefExpression: QueryRoleRefExpressionV1_0_0,
  QueryResourcePackageItem: QueryResourcePackageItemV1_0_0,
  QueryGroupRefExpression: QueryGroupRefExpressionV1_1_0,
  QueryFillRuleExpression: QueryFillRuleExpressionV1_1_0,
  QueryNativeVisualCalc: QueryNativeVisualCalcV1_0_0,
  QuerySparklineDataExpression: QuerySparklineDataExpressionV1_1_0,
  QueryTransformOutputRoleRefExpression: QueryTransformOutputRoleRefExpressionV1_0_0,
  QueryTransformTableRefExpression: QueryTransformTableRefExpressionV1_0_0,
  QueryFilteredEvalExpression: QueryFilteredEvalExpressionV1_1_0,
  QueryScopedEvalExpression: QueryScopedEvalExpressionV1_1_0,
  QueryFloorExpression: QueryFloorExpressionV1_1_0,
  QueryArithmeticExpression: QueryArithmeticExpressionV1_1_0,
  ArithmeticOperatorKind: ArithmeticOperatorKindV1_0_0,
  QueryAnyValueExpression: QueryAnyValueExpressionV1_0_0,
  QueryDefaultValueExpression: QueryDefaultValueExpressionV1_0_0,
  QueryNowExpression: QueryNowExpressionV1_0_0,
  QueryDateAddExpression: QueryDateAddExpressionV1_1_0,
  TimeUnit: TimeUnitV1_0_0,
  QueryDateSpanExpression: QueryDateSpanExpressionV1_1_0,
  QueryLiteralExpression: QueryLiteralExpressionV1_0_0,
  QueryExistsExpression: QueryExistsExpressionV1_1_0,
  QueryStartsWithExpression: QueryStartsWithExpressionV1_1_0,
  QueryContainsExpression: QueryContainsExpressionV1_1_0,
  QueryNotExpression: QueryNotExpressionV1_1_0,
  QueryComparisonExpression: QueryComparisonExpressionV1_1_0,
  QueryComparisonKind: QueryComparisonKindV1_0_0,
  QueryBinaryExpression: QueryBinaryExpressionV1_1_0,
  QueryInExpression: QueryInExpressionV1_1_0,
  QueryBetweenExpression: QueryBetweenExpressionV1_1_0,
  QueryDiscretizeExpression: QueryDiscretizeExpressionV1_1_0,
  QuerySubqueryExpression: QuerySubqueryExpressionV1_1_0,
  QueryDefinition: QueryDefinitionV1_1_0,
  QueryTransform: QueryTransformV1_1_0,
  QueryTransformOutput: QueryTransformOutputV1_1_0,
  QueryTransformTable: QueryTransformTableV1_1_0,
  QueryTransformTableColumn: QueryTransformTableColumnV1_1_0,
  QueryTransformInput: QueryTransformInputV1_1_0,
  Axis: AxisV1_1_0,
  AxisGroup: AxisGroupV1_1_0,
  QuerySortClause: QuerySortClauseV1_1_0,
  EntitySource: EntitySourceV1_1_0,
  QueryPropertyVariationSourceExpression: QueryPropertyVariationSourceExpressionV1_1_0,
  QueryHierarchyLevelExpression: QueryHierarchyLevelExpressionV1_1_0,
  QueryHierarchyExpression: QueryHierarchyExpressionV1_1_0,
  QueryPercentileExpression: QueryPercentileExpressionV1_1_0,
  QueryAggregationExpression: QueryAggregationExpressionV1_1_0,
  QueryAggregateFunction: QueryAggregateFunctionV1_0_0,
  QueryMaxExpression: QueryMaxExpressionV1_1_0,
  IncludeAllTypes: IncludeAllTypesV1_0_0,
  QueryMinExpression: QueryMinExpressionV1_1_0,
  QueryMeasureExpression: QueryMeasureExpressionV1_1_0,
  QueryColumnExpression: QueryColumnExpressionV1_1_0,
  QuerySourceRefExpression: QuerySourceRefExpressionV1_0_0,
  StandaloneSourceRefExpression: StandaloneSourceRefExpressionV1_0_0,
} as const;

export { SemanticQuery as SemanticQueryV1_1_0 } from "./shared.js";
