import { Schema } from "effect";
import {
  ArithmeticOperatorKind,
  AxisGroupV1_3_0,
  AxisV1_3_0,
  EntitySourceV1_3_0,
  IncludeAllTypes,
  QueryAggregateFunction,
  QueryAggregationExpressionV1_3_0,
  QueryAnyValueExpression,
  QueryArithmeticExpressionV1_3_0,
  QueryBetweenExpressionV1_3_0,
  QueryBinaryExpressionV1_3_0,
  QueryCaseV1_3_0,
  QueryColumnExpressionV1_3_0,
  QueryComparisonExpressionV1_3_0,
  QueryComparisonKind,
  QueryConditionalExpressionV1_3_0,
  QueryDateAddExpressionV1_3_0,
  QueryDateSpanExpressionV1_3_0,
  QueryDefinitionV1_3_0,
  QueryDiscretizeExpressionV1_3_0,
  QueryExpressionContainerV1_3_0,
  QueryExpressionContentCacheV1_3_0,
  QueryFillRuleExpressionV1_3_0,
  QueryFilteredEvalExpressionV1_3_0,
  QueryFilterV1_3_0,
  QueryFloorExpressionV1_3_0,
  QueryGroupRefExpressionV1_3_0,
  QueryHierarchyExpressionV1_3_0,
  QueryHierarchyLevelExpressionV1_3_0,
  QueryInExpressionV1_3_0,
  QueryLiteralExpression,
  QueryMaxExpressionV1_3_0,
  QueryNativeColumnV1_3_0,
  QueryNativeMeasureV1_3_0,
  QueryNativeVisualCalcV1_2_0,
  QueryNotExpressionV1_3_0,
  QueryNowExpression,
  QueryPercentileExpressionV1_3_0,
  QueryPropertyVariationSourceExpressionV1_3_0,
  QueryResourcePackageItem,
  QueryRoleRefExpression,
  QueryScopedEvalExpressionV1_3_0,
  QuerySelectRefExpression,
  QuerySortClauseV1_3_0,
  QuerySourceRefExpression,
  QuerySparklineDataExpressionV1_3_0,
  QuerySubqueryExpressionV1_3_0,
  QuerySummaryValueRefExpression,
  QueryThemeDataColorExpression,
  QueryTransformInputV1_3_0,
  QueryTransformOutputRoleRefExpression,
  QueryTransformOutputV1_3_0,
  QueryTransformTableColumnV1_3_0,
  QueryTransformTableV1_3_0,
  QueryTransformV1_3_0,
  QueryVisualTopNExpression,
  SortDirection,
  StandaloneSourceRefExpression,
  TimeUnit,
} from "./shared.js";
import { closed } from "../shared.js";

export type FilterDefinitionV1_3_0 = {
  readonly Version?: 2;
  readonly From: ReadonlyArray<EntitySourceV1_3_0>;
  readonly Where: ReadonlyArray<QueryFilterV1_3_0>;
};

export const FilterDefinitionV1_3_0: Schema.Codec<FilterDefinitionV1_3_0> =
  closed({
    Version: Schema.optionalKey(Schema.Literal(2)),
    From: Schema.Array(Schema.suspend(() => EntitySourceV1_3_0)),
    Where: Schema.Array(Schema.suspend(() => QueryFilterV1_3_0)),
  });

export const SemanticQueryDefinitionsV1_3_0 = {
  FilterDefinition: FilterDefinitionV1_3_0,
  QueryFilter: QueryFilterV1_3_0,
  QueryExpressionContainer: QueryExpressionContainerV1_3_0,
  QueryVisualTopNExpression: QueryVisualTopNExpression,
  QueryNativeColumn: QueryNativeColumnV1_3_0,
  QueryExpressionContentCache: QueryExpressionContentCacheV1_3_0,
  QueryNativeMeasure: QueryNativeMeasureV1_3_0,
  QueryConditionalExpression: QueryConditionalExpressionV1_3_0,
  QueryCase: QueryCaseV1_3_0,
  QueryThemeDataColorExpression: QueryThemeDataColorExpression,
  QuerySelectRefExpression: QuerySelectRefExpression,
  QueryAllRolesRefExpression: QueryNowExpression,
  QuerySummaryValueRefExpression: QuerySummaryValueRefExpression,
  QueryRoleRefExpression: QueryRoleRefExpression,
  QueryResourcePackageItem: QueryResourcePackageItem,
  QueryGroupRefExpression: QueryGroupRefExpressionV1_3_0,
  QueryFillRuleExpression: QueryFillRuleExpressionV1_3_0,
  QueryNativeVisualCalc: QueryNativeVisualCalcV1_2_0,
  QuerySparklineDataExpression: QuerySparklineDataExpressionV1_3_0,
  QueryTransformOutputRoleRefExpression: QueryTransformOutputRoleRefExpression,
  QueryTransformTableRefExpression: QuerySourceRefExpression,
  QueryFilteredEvalExpression: QueryFilteredEvalExpressionV1_3_0,
  QueryScopedEvalExpression: QueryScopedEvalExpressionV1_3_0,
  QueryFloorExpression: QueryFloorExpressionV1_3_0,
  QueryArithmeticExpression: QueryArithmeticExpressionV1_3_0,
  ArithmeticOperatorKind: ArithmeticOperatorKind,
  QueryAnyValueExpression: QueryAnyValueExpression,
  QueryDefaultValueExpression: QueryNowExpression,
  QueryNowExpression: QueryNowExpression,
  QueryDateAddExpression: QueryDateAddExpressionV1_3_0,
  TimeUnit: TimeUnit,
  QueryDateSpanExpression: QueryDateSpanExpressionV1_3_0,
  QueryLiteralExpression: QueryLiteralExpression,
  QueryExistsExpression: QueryNotExpressionV1_3_0,
  QueryStartsWithExpression: QueryBinaryExpressionV1_3_0,
  QueryContainsExpression: QueryBinaryExpressionV1_3_0,
  QueryNotExpression: QueryNotExpressionV1_3_0,
  QueryComparisonExpression: QueryComparisonExpressionV1_3_0,
  QueryComparisonKind: QueryComparisonKind,
  QueryBinaryExpression: QueryBinaryExpressionV1_3_0,
  QueryInExpression: QueryInExpressionV1_3_0,
  QueryBetweenExpression: QueryBetweenExpressionV1_3_0,
  QueryDiscretizeExpression: QueryDiscretizeExpressionV1_3_0,
  QuerySubqueryExpression: QuerySubqueryExpressionV1_3_0,
  QueryDefinition: QueryDefinitionV1_3_0,
  QueryTransform: QueryTransformV1_3_0,
  QueryTransformOutput: QueryTransformOutputV1_3_0,
  QueryTransformTable: QueryTransformTableV1_3_0,
  QueryTransformTableColumn: QueryTransformTableColumnV1_3_0,
  QueryTransformInput: QueryTransformInputV1_3_0,
  Axis: AxisV1_3_0,
  AxisGroup: AxisGroupV1_3_0,
  QuerySortClause: QuerySortClauseV1_3_0,
  SortDirection: SortDirection,
  EntitySource: EntitySourceV1_3_0,
  QueryPropertyVariationSourceExpression:
    QueryPropertyVariationSourceExpressionV1_3_0,
  QueryHierarchyLevelExpression: QueryHierarchyLevelExpressionV1_3_0,
  QueryHierarchyExpression: QueryHierarchyExpressionV1_3_0,
  QueryPercentileExpression: QueryPercentileExpressionV1_3_0,
  QueryAggregationExpression: QueryAggregationExpressionV1_3_0,
  QueryAggregateFunction: QueryAggregateFunction,
  QueryMaxExpression: QueryMaxExpressionV1_3_0,
  IncludeAllTypes: IncludeAllTypes,
  QueryMinExpression: QueryMaxExpressionV1_3_0,
  QueryMeasureExpression: QueryColumnExpressionV1_3_0,
  QueryColumnExpression: QueryColumnExpressionV1_3_0,
  QuerySourceRefExpression: QuerySourceRefExpression,
  StandaloneSourceRefExpression: StandaloneSourceRefExpression,
} as const;

export {
  QueryFilterV1_3_0,
  QueryExpressionContainerV1_3_0,
  QueryVisualTopNExpression as QueryVisualTopNExpressionV1_3_0,
  QueryNativeColumnV1_3_0,
  QueryExpressionContentCacheV1_3_0,
  QueryNativeMeasureV1_3_0,
  QueryConditionalExpressionV1_3_0,
  QueryCaseV1_3_0,
  QueryThemeDataColorExpression as QueryThemeDataColorExpressionV1_3_0,
  QuerySelectRefExpression as QuerySelectRefExpressionV1_3_0,
  QueryNowExpression as QueryAllRolesRefExpressionV1_3_0,
  QuerySummaryValueRefExpression as QuerySummaryValueRefExpressionV1_3_0,
  QueryRoleRefExpression as QueryRoleRefExpressionV1_3_0,
  QueryResourcePackageItem as QueryResourcePackageItemV1_3_0,
  QueryGroupRefExpressionV1_3_0,
  QueryFillRuleExpressionV1_3_0,
  QueryNativeVisualCalcV1_2_0 as QueryNativeVisualCalcV1_3_0,
  QuerySparklineDataExpressionV1_3_0,
  QueryTransformOutputRoleRefExpression as QueryTransformOutputRoleRefExpressionV1_3_0,
  QuerySourceRefExpression as QueryTransformTableRefExpressionV1_3_0,
  QueryFilteredEvalExpressionV1_3_0,
  QueryScopedEvalExpressionV1_3_0,
  QueryFloorExpressionV1_3_0,
  QueryArithmeticExpressionV1_3_0,
  ArithmeticOperatorKind as ArithmeticOperatorKindV1_3_0,
  QueryAnyValueExpression as QueryAnyValueExpressionV1_3_0,
  QueryNowExpression as QueryDefaultValueExpressionV1_3_0,
  QueryNowExpression as QueryNowExpressionV1_3_0,
  QueryDateAddExpressionV1_3_0,
  TimeUnit as TimeUnitV1_3_0,
  QueryDateSpanExpressionV1_3_0,
  QueryLiteralExpression as QueryLiteralExpressionV1_3_0,
  QueryNotExpressionV1_3_0 as QueryExistsExpressionV1_3_0,
  QueryBinaryExpressionV1_3_0 as QueryStartsWithExpressionV1_3_0,
  QueryBinaryExpressionV1_3_0 as QueryContainsExpressionV1_3_0,
  QueryNotExpressionV1_3_0,
  QueryComparisonExpressionV1_3_0,
  QueryComparisonKind as QueryComparisonKindV1_3_0,
  QueryBinaryExpressionV1_3_0,
  QueryInExpressionV1_3_0,
  QueryBetweenExpressionV1_3_0,
  QueryDiscretizeExpressionV1_3_0,
  QuerySubqueryExpressionV1_3_0,
  QueryDefinitionV1_3_0,
  QueryTransformV1_3_0,
  QueryTransformOutputV1_3_0,
  QueryTransformTableV1_3_0,
  QueryTransformTableColumnV1_3_0,
  QueryTransformInputV1_3_0,
  AxisV1_3_0,
  AxisGroupV1_3_0,
  QuerySortClauseV1_3_0,
  SortDirection as SortDirectionV1_3_0,
  EntitySourceV1_3_0,
  QueryPropertyVariationSourceExpressionV1_3_0,
  QueryHierarchyLevelExpressionV1_3_0,
  QueryHierarchyExpressionV1_3_0,
  QueryPercentileExpressionV1_3_0,
  QueryAggregationExpressionV1_3_0,
  QueryAggregateFunction as QueryAggregateFunctionV1_3_0,
  QueryMaxExpressionV1_3_0,
  IncludeAllTypes as IncludeAllTypesV1_3_0,
  QueryMaxExpressionV1_3_0 as QueryMinExpressionV1_3_0,
  QueryColumnExpressionV1_3_0 as QueryMeasureExpressionV1_3_0,
  QueryColumnExpressionV1_3_0,
  QuerySourceRefExpression as QuerySourceRefExpressionV1_3_0,
  StandaloneSourceRefExpression as StandaloneSourceRefExpressionV1_3_0,
  SemanticQuery as SemanticQueryV1_3_0,
} from "./shared.js";
