import { Schema } from "effect";
import {
  ArithmeticOperatorKind,
  AxisGroupV1_2_0,
  AxisV1_2_0,
  EntitySourceV1_2_0,
  IncludeAllTypes,
  QueryAggregateFunction,
  QueryAggregationExpressionV1_2_0,
  QueryAnyValueExpression,
  QueryArithmeticExpressionV1_2_0,
  QueryBetweenExpressionV1_2_0,
  QueryBinaryExpressionV1_2_0,
  QueryCaseV1_2_0,
  QueryColumnExpressionV1_2_0,
  QueryComparisonExpressionV1_2_0,
  QueryComparisonKind,
  QueryConditionalExpressionV1_2_0,
  QueryDateAddExpressionV1_2_0,
  QueryDateSpanExpressionV1_2_0,
  QueryDefinitionV1_2_0,
  QueryDiscretizeExpressionV1_2_0,
  QueryExpressionContainerV1_2_0,
  QueryExpressionContentCacheV1_2_0,
  QueryFillRuleExpressionV1_2_0,
  QueryFilteredEvalExpressionV1_2_0,
  QueryFilterV1_2_0,
  QueryFloorExpressionV1_2_0,
  QueryGroupRefExpressionV1_2_0,
  QueryHierarchyExpressionV1_2_0,
  QueryHierarchyLevelExpressionV1_2_0,
  QueryInExpressionV1_2_0,
  QueryLiteralExpression,
  QueryMaxExpressionV1_2_0,
  QueryNativeColumnV1_2_0,
  QueryNativeMeasureV1_2_0,
  QueryNativeVisualCalcV1_2_0,
  QueryNotExpressionV1_2_0,
  QueryNowExpression,
  QueryPercentileExpressionV1_2_0,
  QueryPropertyVariationSourceExpressionV1_2_0,
  QueryResourcePackageItem,
  QueryRoleRefExpression,
  QueryScopedEvalExpressionV1_2_0,
  QuerySelectRefExpression,
  QuerySortClauseV1_2_0,
  QuerySourceRefExpression,
  QuerySparklineDataExpressionV1_2_0,
  QuerySubqueryExpressionV1_2_0,
  QuerySummaryValueRefExpression,
  QueryThemeDataColorExpression,
  QueryTransformInputV1_2_0,
  QueryTransformOutputRoleRefExpression,
  QueryTransformOutputV1_2_0,
  QueryTransformTableColumnV1_2_0,
  QueryTransformTableV1_2_0,
  QueryTransformV1_2_0,
  QueryVisualTopNExpression,
  StandaloneSourceRefExpression,
  TimeUnit,
} from "./shared.js";
import { closed } from "../shared.js";

export type FilterDefinitionV1_2_0 = {
  readonly Version?: 2;
  readonly From: ReadonlyArray<EntitySourceV1_2_0>;
  readonly Where: ReadonlyArray<QueryFilterV1_2_0>;
};

export const FilterDefinitionV1_2_0: Schema.Codec<FilterDefinitionV1_2_0> =
  closed({
    Version: Schema.optionalKey(Schema.Literal(2)),
    From: Schema.Array(Schema.suspend(() => EntitySourceV1_2_0)),
    Where: Schema.Array(Schema.suspend(() => QueryFilterV1_2_0)),
  });

export const SemanticQueryDefinitionsV1_2_0 = {
  FilterDefinition: FilterDefinitionV1_2_0,
  QueryFilter: QueryFilterV1_2_0,
  QueryExpressionContainer: QueryExpressionContainerV1_2_0,
  QueryVisualTopNExpression: QueryVisualTopNExpression,
  QueryNativeColumn: QueryNativeColumnV1_2_0,
  QueryExpressionContentCache: QueryExpressionContentCacheV1_2_0,
  QueryNativeMeasure: QueryNativeMeasureV1_2_0,
  QueryConditionalExpression: QueryConditionalExpressionV1_2_0,
  QueryCase: QueryCaseV1_2_0,
  QueryThemeDataColorExpression: QueryThemeDataColorExpression,
  QuerySelectRefExpression: QuerySelectRefExpression,
  QueryAllRolesRefExpression: QueryNowExpression,
  QuerySummaryValueRefExpression: QuerySummaryValueRefExpression,
  QueryRoleRefExpression: QueryRoleRefExpression,
  QueryResourcePackageItem: QueryResourcePackageItem,
  QueryGroupRefExpression: QueryGroupRefExpressionV1_2_0,
  QueryFillRuleExpression: QueryFillRuleExpressionV1_2_0,
  QueryNativeVisualCalc: QueryNativeVisualCalcV1_2_0,
  QuerySparklineDataExpression: QuerySparklineDataExpressionV1_2_0,
  QueryTransformOutputRoleRefExpression: QueryTransformOutputRoleRefExpression,
  QueryTransformTableRefExpression: QuerySourceRefExpression,
  QueryFilteredEvalExpression: QueryFilteredEvalExpressionV1_2_0,
  QueryScopedEvalExpression: QueryScopedEvalExpressionV1_2_0,
  QueryFloorExpression: QueryFloorExpressionV1_2_0,
  QueryArithmeticExpression: QueryArithmeticExpressionV1_2_0,
  ArithmeticOperatorKind: ArithmeticOperatorKind,
  QueryAnyValueExpression: QueryAnyValueExpression,
  QueryDefaultValueExpression: QueryNowExpression,
  QueryNowExpression: QueryNowExpression,
  QueryDateAddExpression: QueryDateAddExpressionV1_2_0,
  TimeUnit: TimeUnit,
  QueryDateSpanExpression: QueryDateSpanExpressionV1_2_0,
  QueryLiteralExpression: QueryLiteralExpression,
  QueryExistsExpression: QueryNotExpressionV1_2_0,
  QueryStartsWithExpression: QueryBinaryExpressionV1_2_0,
  QueryContainsExpression: QueryBinaryExpressionV1_2_0,
  QueryNotExpression: QueryNotExpressionV1_2_0,
  QueryComparisonExpression: QueryComparisonExpressionV1_2_0,
  QueryComparisonKind: QueryComparisonKind,
  QueryBinaryExpression: QueryBinaryExpressionV1_2_0,
  QueryInExpression: QueryInExpressionV1_2_0,
  QueryBetweenExpression: QueryBetweenExpressionV1_2_0,
  QueryDiscretizeExpression: QueryDiscretizeExpressionV1_2_0,
  QuerySubqueryExpression: QuerySubqueryExpressionV1_2_0,
  QueryDefinition: QueryDefinitionV1_2_0,
  QueryTransform: QueryTransformV1_2_0,
  QueryTransformOutput: QueryTransformOutputV1_2_0,
  QueryTransformTable: QueryTransformTableV1_2_0,
  QueryTransformTableColumn: QueryTransformTableColumnV1_2_0,
  QueryTransformInput: QueryTransformInputV1_2_0,
  Axis: AxisV1_2_0,
  AxisGroup: AxisGroupV1_2_0,
  QuerySortClause: QuerySortClauseV1_2_0,
  EntitySource: EntitySourceV1_2_0,
  QueryPropertyVariationSourceExpression:
    QueryPropertyVariationSourceExpressionV1_2_0,
  QueryHierarchyLevelExpression: QueryHierarchyLevelExpressionV1_2_0,
  QueryHierarchyExpression: QueryHierarchyExpressionV1_2_0,
  QueryPercentileExpression: QueryPercentileExpressionV1_2_0,
  QueryAggregationExpression: QueryAggregationExpressionV1_2_0,
  QueryAggregateFunction: QueryAggregateFunction,
  QueryMaxExpression: QueryMaxExpressionV1_2_0,
  IncludeAllTypes: IncludeAllTypes,
  QueryMinExpression: QueryMaxExpressionV1_2_0,
  QueryMeasureExpression: QueryColumnExpressionV1_2_0,
  QueryColumnExpression: QueryColumnExpressionV1_2_0,
  QuerySourceRefExpression: QuerySourceRefExpression,
  StandaloneSourceRefExpression: StandaloneSourceRefExpression,
} as const;

export {
  QueryFilterV1_2_0,
  QueryExpressionContainerV1_2_0,
  QueryVisualTopNExpression as QueryVisualTopNExpressionV1_2_0,
  QueryNativeColumnV1_2_0,
  QueryExpressionContentCacheV1_2_0,
  QueryNativeMeasureV1_2_0,
  QueryConditionalExpressionV1_2_0,
  QueryCaseV1_2_0,
  QueryThemeDataColorExpression as QueryThemeDataColorExpressionV1_2_0,
  QuerySelectRefExpression as QuerySelectRefExpressionV1_2_0,
  QueryNowExpression as QueryAllRolesRefExpressionV1_2_0,
  QuerySummaryValueRefExpression as QuerySummaryValueRefExpressionV1_2_0,
  QueryRoleRefExpression as QueryRoleRefExpressionV1_2_0,
  QueryResourcePackageItem as QueryResourcePackageItemV1_2_0,
  QueryGroupRefExpressionV1_2_0,
  QueryFillRuleExpressionV1_2_0,
  QueryNativeVisualCalcV1_2_0,
  QuerySparklineDataExpressionV1_2_0,
  QueryTransformOutputRoleRefExpression as QueryTransformOutputRoleRefExpressionV1_2_0,
  QuerySourceRefExpression as QueryTransformTableRefExpressionV1_2_0,
  QueryFilteredEvalExpressionV1_2_0,
  QueryScopedEvalExpressionV1_2_0,
  QueryFloorExpressionV1_2_0,
  QueryArithmeticExpressionV1_2_0,
  ArithmeticOperatorKind as ArithmeticOperatorKindV1_2_0,
  QueryAnyValueExpression as QueryAnyValueExpressionV1_2_0,
  QueryNowExpression as QueryDefaultValueExpressionV1_2_0,
  QueryNowExpression as QueryNowExpressionV1_2_0,
  QueryDateAddExpressionV1_2_0,
  TimeUnit as TimeUnitV1_2_0,
  QueryDateSpanExpressionV1_2_0,
  QueryLiteralExpression as QueryLiteralExpressionV1_2_0,
  QueryNotExpressionV1_2_0 as QueryExistsExpressionV1_2_0,
  QueryBinaryExpressionV1_2_0 as QueryStartsWithExpressionV1_2_0,
  QueryBinaryExpressionV1_2_0 as QueryContainsExpressionV1_2_0,
  QueryNotExpressionV1_2_0,
  QueryComparisonExpressionV1_2_0,
  QueryComparisonKind as QueryComparisonKindV1_2_0,
  QueryBinaryExpressionV1_2_0,
  QueryInExpressionV1_2_0,
  QueryBetweenExpressionV1_2_0,
  QueryDiscretizeExpressionV1_2_0,
  QuerySubqueryExpressionV1_2_0,
  QueryDefinitionV1_2_0,
  QueryTransformV1_2_0,
  QueryTransformOutputV1_2_0,
  QueryTransformTableV1_2_0,
  QueryTransformTableColumnV1_2_0,
  QueryTransformInputV1_2_0,
  AxisV1_2_0,
  AxisGroupV1_2_0,
  QuerySortClauseV1_2_0,
  EntitySourceV1_2_0,
  QueryPropertyVariationSourceExpressionV1_2_0,
  QueryHierarchyLevelExpressionV1_2_0,
  QueryHierarchyExpressionV1_2_0,
  QueryPercentileExpressionV1_2_0,
  QueryAggregationExpressionV1_2_0,
  QueryAggregateFunction as QueryAggregateFunctionV1_2_0,
  QueryMaxExpressionV1_2_0,
  IncludeAllTypes as IncludeAllTypesV1_2_0,
  QueryMaxExpressionV1_2_0 as QueryMinExpressionV1_2_0,
  QueryColumnExpressionV1_2_0 as QueryMeasureExpressionV1_2_0,
  QueryColumnExpressionV1_2_0,
  QuerySourceRefExpression as QuerySourceRefExpressionV1_2_0,
  StandaloneSourceRefExpression as StandaloneSourceRefExpressionV1_2_0,
  SemanticQuery as SemanticQueryV1_2_0,
} from "./shared.js";
